### ISSUE TITLE
Ionic Serve Ionic 2 RC1 not updating the view

### ISSUE THREAD

**Issue by Ghayyas** [driftyco/ionic-app-scripts#228] opened 2016-10-24 12:46 UTC
Hello There Ionic team Im gettting issue regarding Ionic 2 serve.
I run command 1 ` ionic serve `  it opens bowser and display the items.

But When I changed Something in my Html Or Ts Broswer not reload and nothing changed display in browser. 

Also There is Issue with Expermental Decorator.

My Ionic Info:

  
        Your system information:   
         Cordova CLI: 6.3.1 
         Gulp version:  CLI version 3.9.1
          Gulp local:   Local version 3.9.1
          Ionic Framework Version: 2.0.0-rc.1
          Ionic CLI Version: 2.0.0
           Ionic App Lib Version: 2.0.0-beta.20 
           OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04.1 LTS 
           Node Version: v6.2.1   

Im tried to update Ionic using npm but my version remains Same that is  2.0.0

My package.json file

       {
          "name": "rt_sampler",
          "author": "Ionic Framework",
          "homepage": "http://ionicframework.com/",
           "private": true,
           "scripts": {
           "build": "ionic-app-scripts build",
           "watch": "ionic-app-scripts watch",
           "serve:before": "watch",
            "emulate:before": "build",
      
            "deploy:before": "build",
            "build:before": "build",
             "run:before": "build"
          },
             "dependencies": {
             "@angular/common": "2.0.0",
             "@angular/compiler": "2.0.0",
             "@angular/compiler-cli": "0.6.2",
             "@angular/core": "2.0.0",
             "@angular/forms": "2.0.0",
             "@angular/http": "2.0.0",
             "@angular/platform-browser": "2.0.0",
            "@angular/platform-browser-dynamic": "2.0.0",
            "@angular/platform-server": "2.0.0",
           "@ionic/storage": "1.0.3",
          "ionic-angular": "2.0.0-rc.1",
             "ionic-native": "2.2.3",
            "ionicons": "3.0.0",
             "rxjs": "5.0.0-beta.12",
           "zone.js": "0.6.21"
           },
          "devDependencies": {
           "@ionic/app-scripts": "0.0.36",
           "typescript": "^2.0.3"
         },
         "description": "rt_sampler: An Ionic project",
          "cordovaPlugins": [
          "cordova-plugin-device",
           "cordova-plugin-console",
          "cordova-plugin-whitelist",
          "cordova-plugin-splashscreen",
          "cordova-plugin-statusbar",
           "ionic-plugin-keyboard"
         ],
          "cordovaPlatforms": []
     }

Also My tsconfig.json

         {
             "compilerOptions": {
             "allowSyntheticDefaultImports": true,
    "declaration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es6"
    ],
    "module": "es6",
    "moduleResolution": "node",
    "target": "es6",
    "sourceMap": true,
    "noImplicitAny": true,
    "removeComments": false
         },
          "exclude": [
           "node_modules"
         ],
           "compileOnSave": false,
         "atom": {
           "rewriteTsconfig": false
         }
       
![screenshot from 2016-10-24 16-27-28](https://cloud.githubusercontent.com/assets/10868787/19646151/9d51e5c4-9a11-11e6-9239-1d17a06c4b03.png)
}
Getting this Issue in Every Class I created...

**Comment by jgw96** [comment] 2016-10-24 16:26
Hello, thanks for using Ionic! Would you mind updating your install following the directions in [this blog post](http://blog.ionic.io/ionic-2-rc-weekend-updates/) and trying again?

**Comment by Ghayyas** [comment] 2016-10-24 20:27
Hello @jgw96 Thanks for your Reply. After that post I have unistall and install again Etc. Ionic server Works.. But Ts Config Issue Remains same. That is Experimental Decorator. In every Class  I need see this Warning. Even in your Ionic 2 Blank Project.  Please see this Issue..

Thanks.

**Comment by jgw96** [comment] 2016-10-26 15:34
Hello, unfortunately I cannot reproduce that issue with my install of VSCode. Also, there is not much we can do on our side to fix a vscode related issue. I would recommend checking your `userspace` settings on vscode and asking around on our [forums](https://forum.ionicframework.com). Since the original issue has now been solved I am going to close this issue for now. Thanks for using Ionic!

**Closed by jgw96** 2016-10-26 15:34 UTC
Labels: needs_reply
