### ISSUE TITLE
Custom copy config watch fails when default key is empty

### ISSUE THREAD

**Issue by twinj** [driftyco/ionic-app-scripts#676] opened 2017-01-23 09:51 UTC
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
With a custom copy config in package.json, watch fails if a default key is changed to an empty object or is added to the config by default through object assignment.

#### What behavior are you expecting?
I should be able to change default copy behaviour.

**Steps to reproduce:**
1. Add config in package.json
`  
"config": {
    "ionic_copy": "./config/copy.config.js"
  },`

2. Create custom config file

This version is replaced by default. While this is ok behaviour, I should be able to stop it somehow.
```
module.exports = {
}
```

```
module.exports = {
  copyAssets: {},
  copyIndexContent: {},
  copyFonts: { },
  copyPolyfills: {},
  copySwToolbox: {}
}
```
3. run ionic serve

**Which @ionic/app-scripts version are you using?**
1.0.0

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

I was wanting to use the webpack copy plugin to handle my assets for greater environment control. This can still be achieved by proving valid src and destination values in the default keys by copying the same file several times.

Add a flag which will render the object assign invalid or ignore default values which don't have valid src and dest value. Render a warning for all other invalid values.

**Comment by danbucholtz** [comment] 2017-01-23 15:54
@twinj,

This is by design. Perhaps we can extend that design and run the `Object.assign` conditionally, but it will be `true` by default.

No action to take here at this time.

Thanks,
Dan

**Comment by danbucholtz** [comment] 2017-02-17 06:01
Given the lack of discussion, I'm going to close this issue.

Thanks,
Dan

**Closed by danbucholtz** 2017-02-17 06:01 UTC
Labels: priority:low
