### ISSUE TITLE
random error when I try to build

### ISSUE THREAD

**Issue by balasivagnanam** [driftyco/ionic-app-scripts#102] opened 2016-10-06 07:29 UTC
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
I am getting some random errors when I try to live reload in device or run or build for device.
```
ionic build android
ionic run android -l

```
#### What behavior are you expecting?
The same doesn't occur during ionic serve and I can see the app in browser.
But when I try to execute in device. it is very random, works sometimes, doesnt work sometimes. It shows a white screen for a long time and stuck there.

```
ionic build android
ionic run android -l

```

**Which @ionic/app-scripts version are you using?**
Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v6.7.0

**App scripts:**

"_from": "@ionic/app-scripts@latest",
  "_id": "@ionic/app-scripts@0.0.27",
  "_inCache": true,
  "_installable": true,
  "_location": "/@ionic/app-scripts",
  "_nodeVersion": "4.5.0",
  "_npmOperationalInternal": {
    "host": "packages-12-west.internal.npmjs.com",
    "tmp": "tmp/app-scripts-0.0.27.tgz_1475355475934_0.5256864109542221"

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
![image](https://cloud.githubusercontent.com/assets/4233785/19143947/7c124264-8bd9-11e6-9b74-53c0aa2137bf.png)

**Comment by balasivagnanam** [comment] 2016-10-06 08:35
looks like we cant have 2 terminals to simulate?

I had either 
`ionic server `
or 
`npm run watch`

which was giving this error.

Without parallel execution, I could get ngC compilation successfully.

**Comment by jgw96** [comment] 2016-10-06 15:30
Hello, thanks for using Ionic! This is caused by both your `ionic build` command and `ionic serve` both watching and writing files to the same directory at the same time. Im not sure if the use case of having `ionic serve` and `ionic build` or `ionic run` running at the same time is something we want to support, but i will leave this issue open for discussion. Thanks!

**Comment by dmastag** [comment] 2016-10-08 05:22
@balasivagnanam i am having the same error. I solved it by removing the .tmp folder manually. 
Hope that helps!

**Comment by jgw96** [comment] 2016-10-28 15:03
Hello all! I am going to close this issue for now as I cannot repro anymore with the latest beta of app-scripts. We hope to release v0.0.37 today which as I said fixes this. Thanks!

**Closed by jgw96** 2016-10-28 15:03 UTC
Labels: enhancement
