### ISSUE TITLE
apollo library not working in RC0 (rollup+commonjs circular dep issue)

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-app-scripts#67] opened 2016-10-03 00:53 UTC
_From @metzc on October 2, 2016 9:30_

I used the library apollo-client successfully before RC0 in an ionic project. Now the runtime crashes as soon as i import from the apollo library:

> Uncaught TypeError: Cannot read property 'HTTPFetchNetworkInterface' of undefined (anonymous function) @ batchedNetworkInterface.js:75

I digged into this already and it very much looks like this is a problem due to rollup+commonjs, as is also seen with other libraries. In the case of apollo this looks like a circular dependency that the rollup commonjs plugin just can't handle (https://github.com/rollup/rollup-plugin-commonjs/issues/105).

I wonder how the ionic project wants to deal with this? If Rollup isn't compatible with a lot of existing important libraries, i wonder if it is a good fit for a general purpose framework like Ionic? Maybe the good approach of rollup can be combined with some compatibility as suggested in this comment in a similar issue: https://github.com/driftyco/ionic/issues/8356#issuecomment-250785444 

_Copied from original issue: driftyco/ionic#8400_

**Comment by danbucholtz** [comment] 2016-10-03 19:33
@metzc,

What does your import statement look like?  Do you have types for the library?

What does the error message look like?

Thanks,
Dan

**Comment by metzc** [comment] 2016-10-03 20:31
@danbucholtz this happens on a clean new ionic project with just the official apollo initialization code added: http://dev.apollodata.com/angular2/initialization.html

Types are included in the library (there is no compilation error), error message in browser as quoted in my initial bug report.

I think you can easily reproduce it.

Of course this is a rollup issue. The problem: there is a lot of stuff which doesn't work with rollup so maybe there is a more general question here. Suggestion: have a fallback mechanism which can be activated for certain libraries to work around rollup limitations. Please also note discussions on the related apollo-client (and referenced rollup-commonjs) issues.

**Comment by danbucholtz** [comment] 2016-10-05 19:48
All,

We've posted some docs on the subject. Note: They match a version of `@ionic/app-scripts` that will be dropped in the next day or so. 95% of the concepts still apply.

http://ionicframework.com/docs/v2/resources/third-party-libs/
http://ionicframework.com/docs/v2/resources/app-scripts/

[Here's](https://github.com/danbucholtz/ionic-rollup-angularfire2) an example with AngularFire2.
[Here](https://github.com/danbucholtz/ionic-third-party-lib-mega-test/blob/master/package.json) is a project I implemented that has every library in it that Ionic users have reported trouble with. Most of the libraries worked, but a couple did not. [Here](https://docs.google.com/spreadsheets/d/124VhzYm5gHrBowWAUolfOsVBNTcxTELWauAjKKWAUBQ/edit?usp=sharing) is the summary of the findings.

Please let me know how everything goes. Since we posted documentation, we are going to close this issue.

I posted these issues in the apollo-client repo to get it to work with Ionic and Angular.
https://github.com/apollostack/apollo-client/issues/746
https://github.com/apollostack/apollo-client/issues/745

Thanks,
Dan

**Closed by danbucholtz** 2016-10-05 19:48 UTC
Labels: v2

**Comment by metzc** [comment] 2016-10-06 09:48
Thanks for the detailed work on this!

Just wanted to point out that there is still no way (even via script-tag due to lack of a build) to make apollo-client work with ionic rc0, contrary to what you state in the spreadsheet. (apparently you also commented it out in your example project)

**Comment by danbucholtz** [comment] 2016-10-06 14:30
@metzc,

Were you able to get the library built? If I could get it to compile, I can probably get it to work with Rollup.  What is the error message that you're getting?

Thanks,
Dan

**Comment by metzc** [comment] 2016-10-06 17:57
if you clone the apollo-client repo you can "npm run compile:browser" and it generates a build in the "dist" dir. i managed to adapt the deploy script so that it generates a valid npm package for this build file (which worked). using that i could fix another bug via the namedExports in rollup.config.js. apollo-client seems to work then. Problem is: apollo-client-rxjs generates the next problem (again circular dep as it seems):
RxApolloClient.js:5: Uncaught TypeError: Cannot read property 'prototype' of undefined

This library doesn't include a build script so i stopped following that path. What i did now is to fetch the sources of apollo-client, apollo-client-rxjs and angular2-apollo and fixed the circular deps and some version inconsistencies and used those custom versions in npm which for now works. is more a hack though. apollo-client is being refactored so i switch back to official once they are done.
