### ISSUE TITLE
Exiting ionic serve keeps process running in background

### ISSUE THREAD

**Issue by sveinl** [driftyco/ionic-app-scripts#207] opened 2016-10-20 18:14 UTC
When running `ionic serve -b` and exit it hitting `CTRL-C` something keeps running in the background.
When saving a file in the project then this happens (in the window *after* ionic serve are exited with CTRL-C):
```
 (node:7120) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 33): Error: This socket is closed
(node:10268) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: This socket is closed
```

**Which @ionic/app-scripts version are you using?**
0.0.37

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by jgw96** [comment] 2016-10-20 18:16
Hello, thanks for opening an issue with us! Would you mind updating your ionic cli by running `npm install -g ionic` and seeing if this is still an issue?

**Comment by sveinl** [comment] 2016-10-20 18:22
Same problem. Here is my ionic info:

Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.37
OS: Windows 10
Node Version: v6.7.0

**Comment by sveinl** [comment] 2016-10-20 18:25
Ok, this might be an cygwin issue. I was not able to reproduce this using a standard windows cmd-prompt.

**Comment by Luchillo** [comment] 2016-10-22 16:41
Even if it's cygwin it's still an error with the lib, may not be a priority but is worth having it here for future users with same issue.

**Comment by cleever** [comment] 2016-10-22 16:49
Same here. Windows 10 without cygwin.

**Comment by Luchillo** [comment] 2016-10-22 17:29
Without cygwin means git-bash, power shell or just cmd.exe?

**Comment by cleever** [comment] 2016-10-22 18:06
cmd.exe from vscode.

**Comment by danbucholtz** [comment] 2016-10-28 06:26
I have seen this a few times as well on my Mac with Node 4.x lts. We'll look into it.

Thanks,
Dan

**Comment by jgw96** [comment] 2016-10-28 14:54
Hello all! I am going to close this as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/74.

**Closed by jgw96** 2016-10-28 14:54 UTC
Labels: bug
