### ISSUE TITLE
Service Dependency Injection doesn't work always with version 0.0.39

### ISSUE THREAD

**Issue by savanvadalia** [driftyco/ionic-app-scripts#325] opened 2016-11-08 05:35 UTC
#### Short description of the problem:
Service dependency injection doesn't work always with version 0.0.39 (default is webpack with this version), however same code without any changes works fine for version 0.0.36 (default is roll-up with this version).  
I am using Angular 2 barrels to organise my imports. Upon digging up the problem found that the  service getting failed worked fine if I import it as direct file reference. 

#### What behaviour are you expecting?
Service dependency injection should work regardless of webpack, rollup or barrels being used or not.

#### Steps to reproduce:
1. Privately Emailed @danbucholtz the sample code.
2. run npm install on the project and doing ionic serve should give this error in the console
``` 
Uncaught Error: Can't resolve all parameters for LoginComponent: (App, NavController, MenuController, ?, Events, LocalStorageService, ErrorParserService).(…)
```
3.  **May be a Barrel related issue**:  Error will go away if you change the import statement in LoginComponent
import { LoginService } from '../../account';
TO 
import { LoginService } from '../../account/login/login.service'; 
OR 
import { LoginService } from './login.service';
4.  **May be a webpack related issue**: Error on Step 2 will also go away if you downgrade ionic-app-scripts version to 0.0.36. To verify theory undo the code changes on Step-3 and downgrade the version to 0.0.36.

#### Sample Code
```
import { NavController, MenuController, App, Events } from 'ionic-angular';
import { Component } from '@angular/core';

import { LoginService } from '../../account';
import { UserRegistrationComponent } from '../../account/user-registration';
import { DevicesTabComponent } from '../../shared/navigation';
import { LocalStorageService } from '../../shared/storage';
import { LoginResponse } from '../../shared/contracts';
import { ErrorType } from '../../shared/constants';
import { ErrorParserService } from '../../shared/services';

@Component({
    templateUrl: 'login.component.html'
})
export class LoginComponent {

    public email: string;
    public passWord: string;

    public loginResponse: LoginResponse;

    constructor(public app: App, public nav: NavController, public menu: MenuController,
        public loginService: LoginService, public events: Events,
        public localStorageService: LocalStorageService,
        public errorParserService: ErrorParserService) {

        this.loginResponse = new LoginResponse();
    }
```

**Which @ionic/app-scripts version are you using?**
Your system information:
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.39
OS: Windows 7 SP1
Node Version: v6.9.1

**Comment by ramonornela** [comment] 2016-11-08 07:07
I have a problem force bundler ```rollup```

**Comment by danbucholtz** [comment] 2016-11-10 02:48
@savanvadalia,

If you run `ionic serve` does it work correctly? It only errors out on device, right? This seems to be an `ngc` error. Please let me know so we can address the situation.

Thanks,
Dan

**Comment by savanvadalia** [comment] 2016-11-10 02:51
@danbucholtz 

No, if fails on ```ionic serve``` itself.

Thanks 
Savan

**Comment by savanvadalia** [comment] 2016-11-10 03:21
@danbucholtz Also I updated to latest ionic-app-scripts to latest version 0.0.42 and the same issue still persists.

On a side note new build error reporting looks great  :clap: :clap: :clap:

First of all I was expecting my error to be reported and for sec thought why its not working. 
But realised this particular error is a run-time error and not compile time and hence it doesn't show up,

Thanks
Savan

**Comment by savanvadalia** [comment] 2016-11-17 03:27
@danbucholtz  Any updates on this?

Problem still persist in `0.0.44 `with `webpack`. 
Switching back to `rollup` 
OR
importing the file with complete path still works fine with `webpack`.

I hope we some sort of fix for this as  I have used barrels heavily in my project.

**Comment by jgw96** [comment] 2016-11-18 17:52
Hello all! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/315. Thanks!

**Closed by jgw96** 2016-11-18 17:52 UTC
Labels: needs_reply
