### ISSUE TITLE
cordova_not_available on device with livereload

### ISSUE THREAD

**Issue by izee** [driftyco/ionic-app-scripts#427] opened 2016-11-18 09:34 UTC
#### Short description of the problem:
cordova_not_available, loaded cordova.js is mocked from serve host.

#### What behavior are you expecting?
Load cordova.js correctly.
I think launch index.html locally from apk and change load `build files` from serve host will be work.

**Steps to reproduce:**
ionic run android -l

#### System information:

 ordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.7.0
Xcode version: Not installed

**Comment by jgw96** [comment] 2016-11-18 17:20
Hello, would you mind installing the latest version of the ionic cli? This issue was fixed in the latest version. Thanks!

**Closed by jgw96** 2016-11-18 17:20 UTC

**Comment by izee** [comment] 2016-11-21 01:28
@jgw96 Already at the latest version: `Ionic CLI Version: 2.1.12`

**Comment by dejancencelj** [comment] 2016-11-21 21:00
Same here!

**Comment by biesbjerg** [comment] 2016-11-21 21:42
Can we reopen this?

Same issue reported here: https://github.com/driftyco/ionic/issues/9263

**Comment by biesbjerg** [comment] 2016-11-21 21:52
And here: https://github.com/driftyco/ionic-cli/issues/1701

**Comment by dejancencelj** [comment] 2016-11-21 22:13
The problem is that cordova.js contains only

// mock cordova file during development

Does any one knows how to setup production (re)builds during livereload?

**Comment by dejancencelj** [comment] 2016-11-21 22:21
This command just worked for me :)

ionic run android --lirereload --consolelogs

**Comment by dejancencelj** [comment] 2016-11-21 22:23
my packega json

"scripts": {
    "ionic:build": "ionic-app-scripts build ",
    "ionic:serve": "ionic-app-scripts serve",
    "watch": "ionic-app-scripts watch"
  },
  "dependencies": {
    "@angular/common": "2.1.2",
    "@angular/compiler": "2.1.2",
    "@angular/compiler-cli": "2.1.2",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "@types/lodash": "^4.14.38",
    "ionic-angular": "2.0.0-rc.1",
    "ionic-native": "^2.2.3",
    "ionicons": "3.0.0",
    "lodash": "^4.16.6",
    "phaser": "^2.6.2",
    "rxjs": "5.0.0-rc.1",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.46",
    "typescript": "2.0.9"
  },
  "description": "ClipoApp: An Ionic project",
  "config": {
    "ionic_bundler": "webpack"
  },

**Comment by izee** [comment] 2016-11-22 05:39
@jgw96 please reopen this issue.

**Comment by condorman** [comment] 2016-11-23 15:31
@jgw96 please reopen with RC3 not work

**Comment by pjorquera** [comment] 2016-11-23 18:00
@jgw96 please, reopen this issue. I can confirm that with the following `ionic info` is not working:

```
Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v7.1.0
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by jorgerc85** [comment] 2016-11-24 01:08
Same issue here. Output for `ionic info`:

```
Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by jorgerc85** [comment] 2016-11-24 02:32
For anyone with the same problem, issue #467 is related and currently open.

**Comment by hoodaajay99** [comment] 2016-12-14 10:47
Doesn't work with - Ionic App Scripts Version: 0.0.47

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.2
Node Version: v6.7.0
Xcode version: Not installed
