### ISSUE TITLE
WebPack loader issues

### ISSUE THREAD

**Issue by jayeshanandani** [driftyco/ionic-app-scripts#568] opened 2016-12-16 14:12 UTC
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
On some instances even when there are no errors web pack throws: 
`Final loader didn't return a Buffer or String`

#### What behavior are you expecting?
Webpack doesn't throws that error or shows some meaningful message.

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**
0.047

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
ios-deploy version: 1.9.0 
ios-sim version: 5.0.12 
OS: OS X El Capitan
Node Version: v4.6.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by danbucholtz** [comment] 2016-12-16 14:57
Duplicate of https://github.com/driftyco/ionic-app-scripts/issues/466

Going to close and track it there.

Thanks,
Dan

**Closed by danbucholtz** 2016-12-16 14:57 UTC
