### ISSUE TITLE
JS file can't be found  in chrome devtools sources when using @component  templateUrl

### ISSUE THREAD

**Issue by six006** [driftyco/ionic-app-scripts#89] opened 2016-10-04 16:45 UTC
By now,I still can't find a way using *.ts to debug my ionic2 code! 
I find  a temporary solution to debug the  js .

 project ' ionic-commerce-app'  

When using 'ionic build' command ,all src files are compiled and copy to .tmp directory, 
![3](https://cloud.githubusercontent.com/assets/5348170/19083220/dca9604a-8a93-11e6-9b58-9350db2be417.jpg)

 But I found strange thing !

If using sytax @component {templateUrl:'about.html'},we can't find the file in chrome developer tools sources.the code can't be set breakpoint to debug.
![4](https://cloud.githubusercontent.com/assets/5348170/19083432/a1e8fa82-8a94-11e6-91b0-d966aba74ad2.jpg)
![5](https://cloud.githubusercontent.com/assets/5348170/19083433/a1ecbae6-8a94-11e6-8439-0a94194d18a4.jpg)

when I replace the 'templateUrl' to 'template' ,the file can be found in chrome dev sources . and can be set breakpoint to debug.
![1-1](https://cloud.githubusercontent.com/assets/5348170/19083218/dc7666a4-8a93-11e6-9b3c-74c835ebd88a.jpg)
![1](https://cloud.githubusercontent.com/assets/5348170/19083217/dc732822-8a93-11e6-8107-6642149b395f.jpg)

Can't  I using templateUrl in code.If using templateUrl how to debug it.

**Comment by adamdbradley** [comment] 2016-10-06 02:23
Would you be able to update to the latest version? The dev builds no longer use the .tmp directory.

**Comment by six006** [comment] 2016-10-06 02:57
thanks ,I use the latest 0.0.29 ,but it doesn't generate all files 
![1](https://cloud.githubusercontent.com/assets/5348170/19139011/ae723370-8bb3-11e6-9253-551dff7efbf2.jpg)

**Comment by jgw96** [comment] 2016-10-06 15:47
Hello @six006 , thanks for testing! I am going to close this issue as a duplicate of #101 . Thanks!

**Closed by jgw96** 2016-10-06 15:47 UTC
