### ISSUE TITLE
moment.js locales not supported anymore

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic-app-scripts#764] opened 2017-02-17 10:49 UTC
#### Short description of the problem:

I set globally the locale support in app.component.ts. Using the last version of ionic-app-scripts, 1.1.2, using different locales with moment.js seems to doesn't work anymore. When I run the app i always see the formatted dates in english.

#### What behavior are you expecting?

It should be possible to use moment.js with different locales as it always was while building the app with ionic-app-scripts. It's working fine while building an app with ionic-app-scripts  1.1.0

**Steps to reproduce:**
1. See code below to set globally the moment.js locales
2. Build app with ionic-app-scripts 1.1.2
3. Run the app and display/format a date

app.component.ts

    import moment from 'moment';
    
    import 'moment/src/locale/fr';
    import 'moment/src/locale/de';
    import 'moment/src/locale/it';
    
    ....
    
    // After init
    let userLang = navigator.language.split('-')[0];
    userLang = /(de|en|fr|it)/gi.test(userLang) ? userLang : 'en';
    // Here set the locales to use globally
    moment.locale(userLang);

**Which @ionic/app-scripts version are you using?**

1.1.2

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

moment.js version:

"moment": "^2.17.1"

Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.2.1
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by peterpeterparker** [comment] 2017-02-17 13:50
With source-map-explorer I saw that ionic-app-scripts 1.1.2 didn't seems to automatically include the locales.js files in the build, that's why the locales aren't displayed. 

Did I miss a configuration, if yes, how to solve that? If no could you improve that?

<img width="219" alt="capture d ecran 2017-02-17 a 14 49 56" src="https://cloud.githubusercontent.com/assets/16886711/23067605/625da2d6-f520-11e6-90df-d03c0305a8c5.png">

<img width="409" alt="capture d ecran 2017-02-17 a 14 49 45" src="https://cloud.githubusercontent.com/assets/16886711/23067606/6261c14a-f520-11e6-8135-3e3d5a95d8e1.png">

**Comment by danbucholtz** [comment] 2017-02-17 15:20
Do you have the tree shaking optimization turned on? Can you upload a repo so I can reproduce?

Sounds like a bug to me. Seems strange to me, nothing really changed from `1.1.0` to `.1.1.2` that would affect this I don't think.

Thanks,
Dan

**Comment by peterpeterparker** [comment] 2017-02-17 15:30
@danbucholtz no tree shaking, my config:

    "config": {
       "ionic_sass": "./scripts/sass.config.js",
       "ionic_copy": "./scripts/copy.config.js",
      "ionic_source_map_type": "source-map"
   }

it's a private project/repo but if you send me an e-mail to david.dalbusco@outlook.com I would like to grant you the access

**Comment by danbucholtz** [comment] 2017-02-17 23:06
I cannot reproduce this with `1.3.1`. It seems strange too. It doesn't seem like something any of our code would know about or have an impact on. Hmm. Let me know if you run into it again with `1.3.1`. FWIW, I am also using Angular 2.4.5.

Thanks,
Dan

**Comment by peterpeterparker** [comment] 2017-02-18 08:14
@danbucholtz I could reproduce the problem with a blank starter app ... but maybe I just miss something you know

what I do:

1. checkout https://github.com/peterpeterparker/ionic2Moment.git
2. npm install
3. ionic serve
4. in www/build I run source-map-explorer main.js main.js.map

**Comment by danbucholtz** [comment] 2017-02-20 06:53
Try with Angular 2.4.5. I think this issue is resolved.

Thanks,
Dan

**Comment by peterpeterparker** [comment] 2017-02-20 07:39
@danbucholtz gonna try, but actual Ionic version use Angular 2.2.1, isn't that a problem and risky?

**Comment by danbucholtz** [comment] 2017-02-20 15:52
Try it out and let me know how it goes. I think we're releasing Ionic with 2.4.5 Angular on Wednesday. Realistically, it should be fine.

Thanks,
Dan

**Comment by peterpeterparker** [comment] 2017-02-20 19:32
@danbucholtz unfortunately no it doesn't work. I updated the demo app I posted here above with Angular 2.4.5 but still no success, the locales of moment.js aren't in the build. 

Check the demo app, did I miss something?

Thx you in advance for your feedback

P.S.: new source-map-explorer with Angular 2.4.5

<img width="1374" alt="capture d ecran 2017-02-20 a 20 29 27" src="https://cloud.githubusercontent.com/assets/16886711/23139222/9d4de1fc-f7ab-11e6-88db-2fc8029286a5.png">

<img width="1374" alt="capture d ecran 2017-02-20 a 20 29 27" src="https://cloud.githubusercontent.com/assets/16886711/23139215/9a35fe32-f7ab-11e6-89a2-ab8de2431174.png">

**Comment by danbucholtz** [comment] 2017-02-20 19:40
I'll check out your sample app.

Thanks,
Dan

**Comment by Dasiim** [comment] 2017-02-21 06:51
I have the same issue with
Ionic 2.0.0
ionic/app-scripts 1.1.1
Angular 2.2.1
Moment 2.17.1

The issue came when updating ionic-app-scripts from 1.0.0 to 1.0.1.

**Comment by alan-agius4** [comment] 2017-02-21 08:35
Why has this issue been marked as closed when there is no fix for it?

**Comment by danbucholtz** [comment] 2017-02-21 16:10
@alan-agius4,

I haven't been able to recreate it. I am thinking it's a webpack issue, not an Ionic issue.

Thanks,
Dan

**Comment by danbucholtz** [comment] 2017-02-21 21:06
This seems like it's working to me.

<img width="1438" alt="screen shot 2017-02-21 at 3 05 09 pm" src="https://cloud.githubusercontent.com/assets/4680488/23184948/3fc8e4fe-f847-11e6-8153-ca8b9881eb26.png">

**Closed by danbucholtz** 2017-02-21 21:06 UTC

**Comment by peterpeterparker** [comment] 2017-02-22 06:34
@alan-agius4 @Dasiim it seems I found a solution, would be cool if you could try and confirm it.

Till 1.0.0 the locales should had been imported like following:

    import 'moment/src/locale/fr';
    import 'moment/src/locale/de';
    import 'moment/src/locale/it’;

But now it seems that they should be imported like following:

    import 'moment/locale/fr';
    import 'moment/locale/de';
    import 'moment/locale/it’;

I tried these changes with "ionic serve" and "ionic build ios --prod" and both seems to have works well.

Furthermore, there is a really good side effect to that changes, if I understood correctly, now only these locales gonna be loaded in my app and not all the locales like as it was the case, means the build gonna be lighter and means less data to load on the boot time :)

thx for the support @danbucholtz

**Comment by Dasiim** [comment] 2017-02-22 09:00
Yes, it works like that, but it's problematic :/

Ill try to explain my situation a bit:
We are loading the locales dynamically, because we might have different set of locales needed at some particular time. Importing all of them wouldn't make sense(lose performance).
Before that change, moment was able to import all the necessary locales itself. Could it be changed back to that way?
I'm not sure why it works like that(removing "src" from path).
Would it be possible to support the old way also?(probably you know the place where the change happened already)

**Comment by peterpeterparker** [comment] 2017-02-22 09:03
@Dasiim I didn't tried by myself but maybe try then:

    import 'moment/min/locales';

instead of all separate includes

**Comment by Dasiim** [comment] 2017-02-22 09:34
But then Id include all of them while i only need for example 3. We would import 190kb instead of 10kb what we probably need.

**Comment by peterpeterparker** [comment] 2017-02-22 10:25
@Dasiim sorry I don't understand you then. You have got two choices in my point of view:

1. Load all locales (import 'moment/min/locales';)
2. Load a list of specific locales (import 'moment/locale/fr'; import 'moment/locale/de'; etc...)

I displayed both ways here above. I guess that if you want something else you may have to post a question/issue on the moment.js GitHub itself

**Comment by Dasiim** [comment] 2017-02-22 15:03
Before we included the needed locales with webpack and they were imported automatically. Now it seems we need to import them manually which is not good.

**Comment by Dasiim** [comment] 2017-02-27 10:18
Basically we used this before: https://github.com/webpack/webpack/issues/87
Using ContextReplacementPlugin, we imported only the languages that we needed.

**Comment by alexkonovalov** [comment] 2017-03-08 12:59
We found solution with @Dasiim. 
Instead of using `webpack.ContextReplacementPlugin(/moment[\/]locale$/,` /^./(en|cs)$/)` for filtering out the redundant locales (that worked for us before) we now implicitly add them to the list of **Wepback** entry points.
