### ISSUE TITLE
Webpack update 2x slower in 0.0.39 vs 0.0.38

### ISSUE THREAD

**Issue by lleevvyy** [driftyco/ionic-app-scripts#293] opened 2016-11-01 19:41 UTC
#### Short description of the problem:
Yestarday I tried app-scripts v0.0.38 and webpack was blazing fast - update of my project took 5-8sec. Today, after installation of v0.0.39 I see big slow down - the same project, the same change in ts file and it takes 14-16sec. Any idea why the slow down?

#### What behavior are you expecting?
If possible to have the webpack build speed same as in 0.0.38.

**Steps to reproduce:**
1. ionic serve
2. modify any ts file
3. check webpack update time on 0.0.38 and 0.0.39

**Which @ionic/app-scripts version are you using?**
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.39 (or 0.0.38)
OS: Mac OS X El Capitan
Node Version: v6.9.1

**Comment by jgw96** [comment] 2016-11-01 19:43
Hello, thanks for using Ionic! I am going to close this as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/47.

**Closed by jgw96** 2016-11-01 19:43 UTC
