### ISSUE TITLE
issue: www assets not being updated/cleared

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic-app-scripts#183] opened 2016-10-17 13:20 UTC
#### Short description of the problem:
It seems the www/assets folder is not being cleared out and updated with new assets.

#### What behavior are you expecting?
We created a whole bunch of images and added them into the src/assets/images folder. When running `ionic serve` the www folder is populated with the images. Over time the images change, these changes do not appear in the www/assets folder. 

For example:
- Add a logo.png
- Run ionic serve
- Update logo.png by replacing it with a new image. This may come from git pull.
- Run ionic serve again does not update the logo.

Also we deleted a whole bunch of old images from the src folder and all these old ones were still left in www. 

Should the assets folder not be cleaned and recreated every time? Or at the very least compare an MD5 hash of the files and replace ones that have changed, and clear out ones not in parent dir.

**Which @ionic/app-scripts version are you using?**
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v6.8.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by danbucholtz** [comment] 2016-10-17 14:56
@dylanvdmerwe,

I'll chat with Adam about this. I think we intentionally changed this behavior. We may need to revisit as I agree, this doesn't sound like the right behavior.

Thanks for the issue.

Thanks,
Dan

**Comment by jgw96** [comment] 2016-10-17 16:44
Hey @dylanvdmerwe ! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/176 as it is caused by the same issue. I am in the process of testing a fix for this. Thanks!

**Closed by jgw96** 2016-10-17 16:44 UTC
