### ISSUE TITLE
Error running newly created app (v2)

### ISSUE THREAD

**Issue by jthoms1** [driftyco/ionic-app-scripts#253] opened 2016-10-28 01:01 UTC
_From @rodrigograca31 on October 18, 2016 20:33_

#### Short description of the problem:
Error creating new app. (--v2)

#### What behavior are you expecting?
It should "compile" and run the app....

**Steps to reproduce:**
1. ionic start app --v2
2. cd app/
3. ionic platform add android
4. ionic run android

```
Running 'run:before' npm script before run

> ionic-hello-world@ build /home/unknown/git/app
> ionic-app-scripts build

[21:29:52]  ionic-app-scripts 0.0.36 
[21:29:52]  build prod started ... 
[21:29:52]  clean started ... 
[21:29:52]  clean finished in 3 ms 
[21:29:52]  copy started ... 
[21:29:52]  ngc started ... 
[21:29:52]  copy finished in 28 ms 
[21:29:53]  lint started ... 
[21:29:54]  lint finished in 1.23 s 
[21:29:54]  can't resolve module @angular/core/src/di/opaque_token from /home/unknown/git/app/.tmp/index.ts 
[21:29:54]  TypeError: undefined is not a function 
[21:29:54]  ngc failed 
[21:29:54]  ionic-app-script task: "build" 
[21:29:54]  Error: Error 

npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build" "--color"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic-hello-world@ build script 'ionic-app-scripts build'.
npm ERR! This is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build
npm ERR! You can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/unknown/git/app/npm-debug.log
Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

**Post the output of `ionic info` below please**

```
Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
OS: Distributor ID:     LinuxMint Description:  Linux Mint 17.3 Rosa 
Node Version: v0.12.7
```

_Copied from original issue: driftyco/ionic-cli#1562_

**Comment by jthoms1** [comment] 2016-10-28 01:01
_From @rodrigograca31 on October 18, 2016 20:33_

`ionic serve` works fine...

**Comment by jthoms1** [comment] 2016-10-28 01:01
_From @MasterProgrammer200 on October 19, 2016 15:32_

I am having the same issue. 

1. ionic start cutePuppyPics --v2
2. cd cutePuppyPics
3. ionic serve <--- this works!
4. ionic g page myPage <---- error!
![image](https://cloud.githubusercontent.com/assets/10147954/19525435/eb80072a-95ee-11e6-96bb-d1d28a627a9d.png)

5. ionic build <---- error!
![image](https://cloud.githubusercontent.com/assets/10147954/19525482/13ff368a-95ef-11e6-84e9-4f3a8d27e2c4.png)


Ionic Info:
![image](https://cloud.githubusercontent.com/assets/10147954/19525621/934bbabc-95ef-11e6-845e-50de6ad479f2.png)

**Comment by jthoms1** [comment] 2016-10-28 01:01
_From @rodrigograca31 on October 19, 2016 22:4_

@MasterProgrammer200 you should have posted your erro in text so it could be indexed.....
Since you are using Windows this confirms it's not platform specific...

**Comment by danbucholtz** [comment] 2016-10-28 06:15
@rodrigograca31,

This is an `ngc` error. `ngc` has really bad error messages sometimes. Unfortunately, there isn't anything we can do other than work with the Angular team to improve this, so that is what we're doing. I'm going to close this for now.

Thanks,
Dan

**Closed by danbucholtz** 2016-10-28 06:15 UTC

**Comment by rodrigograca31** [comment] 2016-10-28 10:41
`ngc` error?

Yes, they could get better error messages, but how do I solve this problem?

**Comment by danbucholtz** [comment] 2016-10-28 16:10
@rodrigograca31, The issue is in your code, so you need to find out where it is in your code and fix it. Otherwise, the alternative is to not use `ngc` by adding `--dev` to the end of the `build` command in the `scripts` section of package.json.

Thanks,
Dan

**Comment by rodrigograca31** [comment] 2016-10-28 16:14
@danbucholtz On my code? Nope!
This is a brand new app, not even one line was modified!
If you see the "`Steps to reproduce:`" you can see that I create a new app and run it and it doesn't run...
That's a pretty bad experience for a new user....

**Comment by danbucholtz** [comment] 2016-10-29 04:15
@rodrigograca31,

Ahh, we were burned by a semver issue temporarily. Angular made some breaking changes to their compiler. Update your package.json and remove the `^` everywhere, and then do a fresh `npm install`. That will fix it.

Thanks,
Dan

**Comment by swizard** [comment] 2016-10-29 08:53
@danbucholtz I did what you said. 
delete every ^
delete node_moduldes
npm install .

still not working

**Comment by rodrigograca31** [comment] 2016-10-29 19:29
@danbucholtz Still not working like @swizard said ....
Commands run:
```bash
ionic start app4 --v2          <-- app created
cd app4
cordova platform add android
ionic run android              <-- error (just testing if it would work...)
nano package.json              <-- removed ^ from "@ionic/app-scripts" and "typescript"
rm -rf node_modules/           <-- remove the modules folder
npm install                    <-- reinstalled them...
ionic run android              <-- error again....
```

Error: (output from `ionic run android`)
```
Running 'run:before' npm script before run

> ionic-hello-world@ build /home/unknown/git/app4
> ionic-app-scripts build

[20:26:16]  ionic-app-scripts 0.0.36 
[20:26:16]  build prod started ... 
[20:26:16]  clean started ... 
[20:26:16]  clean finished in 13 ms 
[20:26:16]  copy started ... 
[20:26:16]  ngc started ... 
[20:26:16]  copy finished in 73 ms 
[20:26:17]  lint started ... 
[20:26:20]  lint finished in 2.51 s 
[20:26:20]  can't resolve module @angular/core/src/di/opaque_token from /home/unknown/git/app4/.tmp/index.ts 
[20:26:20]  TypeError: undefined is not a function 
[20:26:20]  ngc failed 
[20:26:20]  ionic-app-script task: "build" 
[20:26:20]  Error: Error 

npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build" "--color"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic-hello-world@ build script 'ionic-app-scripts build'.
npm ERR! This is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build
npm ERR! You can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/unknown/git/app4/npm-debug.log
Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

```

**Comment by danbucholtz** [comment] 2016-10-30 04:03
You need to remove the `^` from all entries in the package.json, or atleast anything with an `@angular/xyz` prefix. The issue is `@angular/compiler` or `@angular/compiler-cli` had a breaking change that they did not realize. We compiled `ionic-angular` with `0.6.2` and something in the latest breaks compatibility with it even though it's not supposed to.

Thanks,
Dan

**Comment by rodrigograca31** [comment] 2016-10-30 22:47
There was `^` only on those two palces ("@ionic/app-scripts" and "typescript")

My package.json:

```json
{
  "name": "ionic-hello-world",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "build": "ionic-app-scripts build",
    "watch": "ionic-app-scripts watch",
    "serve:before": "watch",
    "emulate:before": "build",
    "deploy:before": "build",
    "build:before": "build",
    "run:before": "build"
  },
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/compiler-cli": "0.6.2",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/platform-server": "2.0.0",
    "@ionic/storage": "1.1.6",
    "ionic-angular": "2.0.0-rc.1",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.21"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.36",
    "typescript": "2.0.3"
  },
  "description": "app4: An Ionic project",
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": []
}
```

**Comment by danbucholtz** [comment] 2016-10-31 04:47
@rodrigograca31,

Can you provide us a sample repository recreating the issue?

Thanks,
Dan

**Comment by macdasi** [comment] 2016-10-31 11:22
Same problem for me

**Comment by macdasi** [comment] 2016-10-31 11:23
[13:18:08]  ionic-app-scripts 0.0.38
[13:18:08]  build prod started ...
[13:18:08]  clean started ...
[13:18:08]  clean finished in 4 ms
[13:18:08]  copy started ...
[13:18:08]  ngc started ...
[13:18:08]  copy: Error copying "C:\Repos\patient-portal\src\manifest.json" to
            "C:\Repos\patient-portal\www\manifest.json": File not found
[13:18:08]  copy: Error copying "C:\Repos\patient-portal\src\service-worker.js" to
            "C:\Repos\patient-portal\www\service-worker.js": File not found
[13:18:08]  copy finished in 80 ms
[13:18:09]  lint started ...
[13:18:09]  C:\Repos\patient-portal\node_modules\@angular\compiler-cli\src\private_import_compiler.js:10
[13:18:09]  exports.AssetUrl = compiler_1.__compiler_private__.AssetUrl;
[13:18:09]  TypeError: Cannot read property 'AssetUrl' of undefined
[13:18:09]  ngc failed
[13:18:09]  ionic-app-script task: "build"
[13:18:09]  Error: Error

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hadar.m\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-hello-world@ build script 'ionic-app-scripts build'.

**Comment by rodrigograca31** [comment] 2016-10-31 11:29
@danbucholtz Do you want the code that is causing the issue? It's the "standard" code when you create a new app using: `ionic start app4 --v2`

But here you go: (Note: Just removed "node_modules" folder because it had more than 100MB!!! What?)
(and GitHub was complaining about the .zip size...)
[app4.zip](https://github.com/driftyco/ionic-app-scripts/files/561601/app4.zip)

**Comment by rodrigograca31** [comment] 2016-10-31 11:34
@macdasi Your eror seems different.... `[13:18:09] TypeError: Cannot read property 'AssetUrl' of undefined`

and I've also noticed `ionic-app-scripts 0.0.38`

**Comment by rodrigograca31** [comment] 2016-10-31 11:35
@danbucholtz Now you have the `.zip` file but I will include here the `npm-debug.log` file contents:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build',
1 verbose cli   '--color' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild ionic-hello-world@
6 info build ionic-hello-world@
7 verbose unsafe-perm in lifecycle true
8 info ionic-hello-world@ Failed to exec build script
9 verbose stack Error: ionic-hello-world@ build: `ionic-app-scripts build`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid ionic-hello-world@
11 verbose cwd /home/unknown/git/app6
12 error Linux 3.19.0-32-generic
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build" "--color"
14 error node v0.12.7
15 error npm  v2.11.3
16 error code ELIFECYCLE
17 error ionic-hello-world@ build: `ionic-app-scripts build`
17 error Exit status 1
18 error Failed at the ionic-hello-world@ build script 'ionic-app-scripts build'.
18 error This is most likely a problem with the ionic-hello-world package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     ionic-app-scripts build
18 error You can get their info via:
18 error     npm owner ls ionic-hello-world
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by danbucholtz** [comment] 2016-10-31 14:52
@rodrigograca31,

When I run `ionic run android` or `npm run build`, I get the following output:

```
> ionic-hello-world@ build /Users/dan/Downloads/app4
> ionic-app-scripts build

[09:50:59]  ionic-app-scripts 0.0.38
[09:50:59]  build prod started ...
[09:50:59]  clean started ...
[09:50:59]  clean finished in 4 ms
[09:50:59]  copy started ...
[09:50:59]  ngc started ...
[09:50:59]  copy finished in 30 ms
[09:50:59]  lint started ...
[09:51:00]  lint finished in 717 ms
[09:51:10]  ngc finished in 10.48 s
[09:51:10]  webpack started ...
[09:51:15]  webpack finished in 4.98 s
[09:51:15]  uglifyjs started ...
[09:51:15]  sass started ...
[09:51:15]  sass finished in 910 ms
[09:51:15]  cleancss started ...
[09:51:16]  cleancss finished in 972 ms
[09:51:22]  uglifyjs finished in 7.46 s
[09:51:22]  build prod finished in 22.93 s
```

That is the expected output. Are you not seeing that?

Thanks,
Dan

**Comment by ronakkaria** [comment] 2016-10-31 15:02
I didn't have the exact error as @rodrigograca31, but I was getting weird build errors as well (on 0.0.36). `Unrecognized token '@'` etc

Updating to 0.0.38 fixed the issues for me 👍

**Comment by ronakkaria** [comment] 2016-10-31 15:34
Ok it's the darndest thing, but on 0.0.38 the build errors go away, but what used to be the build error shows up on the console on app start.

Pasting the error here just to show how ridiculous it is

<img width="1091" alt="screen shot 2016-10-31 at 8 52 06 pm" src="https://cloud.githubusercontent.com/assets/6488852/19859638/04c4d500-9fac-11e6-8666-a828b59af34f.png">

This is was very similar to the build error I was getting on 0.0.36.

During development I use `livereload`, by running an `npm run watch` on a another terminal, so that changes in `src` are watched for and files are automatically transpiled and copied into the build folder, triggering an update to the `main.js` file. 

If I remove the `HeroService` mentioned in the screenshot of the error above, and remove all references of it, build works fine and there's no console errors. And keeping`livereload` running, if I make the changes to bring back the `HeroService`, the app works fine and there's no error in the console. So something is definitely wrong with the build process.

@danbucholtz Any thoughts?

**Comment by rodrigograca31** [comment] 2016-10-31 18:02
@danbucholtz I get this when I run that command: (0.0.36)

```
> ionic-hello-world@ build /home/unknown/git/app6
> ionic-app-scripts build

[18:00:06]  ionic-app-scripts 0.0.36 
[18:00:06]  build prod started ... 
[18:00:06]  clean started ... 
[18:00:06]  clean finished in 4 ms 
[18:00:06]  copy started ... 
[18:00:06]  ngc started ... 
[18:00:06]  copy finished in 50 ms 
[18:00:07]  lint started ... 
[18:00:09]  lint finished in 1.66 s 
[18:00:09]  can't resolve module @angular/core/src/di/opaque_token from /home/unknown/git/app6/.tmp/index.ts 
[18:00:09]  TypeError: undefined is not a function 
[18:00:09]  ngc failed 
[18:00:09]  ionic-app-script task: "build" 
[18:00:09]  Error: Error 

npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic-hello-world@ build script 'ionic-app-scripts build'.
npm ERR! This is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build
npm ERR! You can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/unknown/git/app6/npm-debug.log
```

I will update to 0.0.38 and let you know if it solves the problem...

**Comment by rodrigograca31** [comment] 2016-10-31 18:07
Upgrading to `0.0.38` didn't solve the issue... :cry:

**Comment by danbucholtz** [comment] 2016-10-31 18:33
@rodrigograca31, can you blow away `node_modules` and verify that `2.0.0` is installed for Angular dependencies and `@angular/compiler-cli` is version `0.6.2`? We haven't seen or heard of this issue before and can't recreate it.

Thanks,
Dan

**Comment by rodrigograca31** [comment] 2016-10-31 19:12
@danbucholtz I've created another test app and the same happens:

```bash
ionic start app7 --v2
cd app7/
rm -rf node_modules/
nano package.json 
npm install
ionic run android 
```

Error output:
```
Running 'run:before' npm script before run

> ionic-hello-world@ build /home/unknown/git/app7
> ionic-app-scripts build

[19:01:15]  ionic-app-scripts 0.0.38 
[19:01:15]  build prod started ... 
[19:01:15]  clean started ... 
[19:01:15]  clean finished in 3 ms 
[19:01:15]  copy started ... 
[19:01:15]  ngc started ... 
[19:01:15]  copy finished in 43 ms 
[19:01:15]  lint started ... 
[19:01:17]  lint finished in 1.38 s 
[19:01:17]  can't resolve module @angular/core/src/di/opaque_token from /home/unknown/git/app7/.tmp/index.ts 
[19:01:17]  TypeError: undefined is not a function 
[19:01:17]  ngc failed 
[19:01:17]  ionic-app-script task: "build" 
[19:01:17]  Error: Error 

npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build" "--color"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic-hello-world@ build script 'ionic-app-scripts build'.
npm ERR! This is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build
npm ERR! You can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/unknown/git/app7/npm-debug.log
Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

`npm-debug.log`:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build',
1 verbose cli   '--color' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild ionic-hello-world@
6 info build ionic-hello-world@
7 verbose unsafe-perm in lifecycle true
8 info ionic-hello-world@ Failed to exec build script
9 verbose stack Error: ionic-hello-world@ build: `ionic-app-scripts build`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid ionic-hello-world@
11 verbose cwd /home/unknown/git/app7
12 error Linux 3.19.0-32-generic
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build" "--color"
14 error node v0.12.7
15 error npm  v2.11.3
16 error code ELIFECYCLE
17 error ionic-hello-world@ build: `ionic-app-scripts build`
17 error Exit status 1
18 error Failed at the ionic-hello-world@ build script 'ionic-app-scripts build'.
18 error This is most likely a problem with the ionic-hello-world package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     ionic-app-scripts build
18 error You can get their info via:
18 error     npm owner ls ionic-hello-world
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

`package.json`: 
```json
{
  "name": "ionic-hello-world",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "build": "ionic-app-scripts build",
    "watch": "ionic-app-scripts watch",
    "serve:before": "watch",
    "emulate:before": "build",
    "deploy:before": "build",
    "build:before": "build",
    "run:before": "build"
  },
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/compiler-cli": "0.6.2",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/platform-server": "2.0.0",
    "@ionic/storage": "1.1.6",
    "ionic-angular": "2.0.0-rc.1",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.21"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.38",
    "typescript": "2.0.6"
  },
  "description": "app7: An Ionic project",
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": []
}
```
Keep in mind that this is a brand new app... (created with: `ionic start app7 --v2`)

**Comment by danbucholtz** [comment] 2016-10-31 20:09
What version of `node` are you using? What version of `npm`? What OS are you using? Is there anything unique about your environment? I have created about 5 projects today and haven't had that issue at all. I think it is something external to Ionic.

Thanks,
Dan

**Comment by rodrigograca31** [comment] 2016-10-31 22:16
@jthoms1 posted my original `ionic info` output but I will add it again:

```
--------------------------------

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.38
OS: Distributor ID:     LinuxMint Description:  Linux Mint 17.3 Rosa 
Node Version: v0.12.7

--------------------------------
```

**Comment by danbucholtz** [comment] 2016-11-01 02:27
@rodrigograca31,

We don't support that version of Node.js anymore. Please update to the [latest LTS release](https://nodejs.org/dist/v6.9.1/node-v6.9.1.pkg). I think that will resolve your issues.

Thanks,
Dan

**Comment by rodrigograca31** [comment] 2016-11-01 11:42
Ok.... It's solved. I've used the following commands:

`node -v`   <-- v0.12.7
```
sudo npm install n -g
sudo n stable
```
`node -v`   <-- v7.0.0

 :tada:  :tada:  :tada: 
:confetti_ball: :confetti_ball: :confetti_ball:

@danbucholtz Thanks! Have some: :cake: 
Now the world will have another app! (I will make millions with this app! or not... :cry:)

**Comment by rodrigograca31** [comment] 2016-11-01 11:43
Now `ionic run android` executes normally.

**Comment by danbucholtz** [comment] 2016-11-01 16:07
@rodrigograca31, glad to hear it! Have a good day and happy hacking!

Thanks,
Dan

**Comment by kchat001** [comment] 2016-12-05 19:27
Hi Dan,
it seems that I still have a similar problem. Today I am migrating from beta.37 to rc3 and I get some weird errors when doing
`ionic build android`
`ionic serve` works absolutely fine and the app starts in the browser. But doing a built I get the following error:

`
[20:08:11]  ionic-app-scripts 0.0.46
[20:08:11]  build prod started ...
[20:08:11]  clean started ...
[20:08:11]  clean finished in 4 ms
[20:08:11]  copy started ...
[20:08:11]  ngc started ...
[20:08:11]  copy: Error copying
            "/Users/me/projects/migration/myApp/node_modules/ionic-angular/fonts" to
            "/Users/me/projects/migration/myApp/www/assets/fonts"
[20:08:11]  copy finished in 118 ms
[20:08:26]  Error: Error at
            /Users/me/projects/migration/myApp/.tmp/pages/welcome/welcome.ngfactory.ts:328:40
[20:08:26]  Property 'rootPage' does not exist on type 'WelcomePage'.
[20:08:26]  Error at
            /Users/me/projects/migration/myApp/.tmp/pages/nav-frame/nav-frame.ngfactory.ts:454:149
[20:08:26]  Argument of type 'Date' is not assignable to parameter of type 'string'.
[20:08:26]  Error at
            /Users/me/projects/migration/myApp/.tmp/pages/nav-frame/nav-frame.ngfactory.ts:454:378
[20:08:26]  Argument of type 'Date' is not assignable to parameter of type 'string'.
[20:08:26]  Error at
            /Users/me/projects/migration/myApp/.tmp/pages/depots/details/details.ngfactory.ts:525:166
[20:08:26]  Supplied parameters do not match any signature of call target.
...`

It seems like some kind of code error, but they not only do not make any sense, there isn't much information on where exactly that problem is, since `welcome.ngfactory.ts` is a temporary, generated file. And I do not have nor do I need a rootPage in it. With the beta I did not have these issues and it worked on Android and iOS.
Am I missing something?
Any help would be awesome.
Best regards,
Khalid

**Comment by kchat001** [comment] 2016-12-05 19:28
My Ionic info is:

`
Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: 1.9.0
ios-sim version: 5.0.12
OS: OS X El Capitan
Node Version: v6.4.0
Xcode version: Xcode 7.3.1 Build version 7D1014
`

**Comment by kchat001** [comment] 2016-12-06 10:05
Hi,
just an update to my problem:

These were indeed code issues. It was just confusing to suddenly have such a strict type checking that wasn't there before, as well as the fact that the build result is inconsistent with the ionic serve result, which just works.

Maybe the ionic serve result can be adjusted in the future to behave similarly, so one may not be bitten later on.

**Comment by erikacb** [comment] 2016-12-12 20:03
I updated node to the latest version and then I got the following message:

> [17:54:36]  ionic-app-script task: "build" 
> [17:54:36]  Error: "main.dev.ts" and "main.prod.ts" have been deprecated. Please create a new file "main.ts" containing 
>             the content of "main.dev.ts", and then delete the deprecated files. For more information, please see the 
>             default Ionic project main.ts file here: 
>             https://github.com/driftyco/ionic2-app-base/tree/master/src/app/main.ts 

So, I created a main.ts file. I made a CTRL C CTRL V from main.dev.ts to main.ts and that's it :)

**Comment by chaudhary27** [comment] 2017-04-11 04:31
I have the same issue when I run **ionic run android -l**
Here are the logs: 
--------------------------------------
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'ionic:serve',
1 verbose cli   '--',
1 verbose cli   '--v2',
1 verbose cli   '--runLivereload',
1 verbose cli   '--isPlatformServe',
1 verbose cli   '--livereload',
1 verbose cli   '--port',
1 verbose cli   '8100',
1 verbose cli   '--livereload-port',
1 verbose cli   '35729',
1 verbose cli   '--address',
1 verbose cli   '192.168.1.7',
1 verbose cli   '--iscordovaserve',
1 verbose cli   '--nobrowser' ]
2 info using npm@4.1.2
3 info using node@v4.4.2
4 verbose run-script [ 'preionic:serve', 'ionic:serve', 'postionic:serve' ]
5 info lifecycle ionic-hello-world@~preionic:serve: ionic-hello-world@
6 silly lifecycle ionic-hello-world@~preionic:serve: no script for preionic:serve, continuing
7 info lifecycle ionic-hello-world@~ionic:serve: ionic-hello-world@
8 verbose lifecycle ionic-hello-world@~ionic:serve: unsafe-perm in lifecycle true
9 verbose lifecycle ionic-hello-world@~ionic:serve: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/faisalfarooq/Desktop/the_internet/ResSeniorIonic/node_modules/.bin:/Users/faisalfarooq/.rvm/gems/ruby-2.3.3/bin:/Users/faisalfarooq/.rvm/gems/ruby-2.3.3@global/bin:/Users/faisalfarooq/.rvm/rubies/ruby-2.3.3/bin:/Users/faisalfarooq/anaconda/bin:/Users/faisalfarooq/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Users/faisalfarooq/.rvm/bin
10 verbose lifecycle ionic-hello-world@~ionic:serve: CWD: /Users/faisalfarooq/Desktop/the_internet/ResSeniorIonic
11 silly lifecycle ionic-hello-world@~ionic:serve: Args: [ '-c',
11 silly lifecycle   'ionic-app-scripts serve "--v2" "--runLivereload" "--isPlatformServe" "--livereload" "--port" "8100" "--livereload-port" "35729" "--address" "192.168.1.7" "--iscordovaserve" "--nobrowser"' ]
12 silly lifecycle ionic-hello-world@~ionic:serve: Returned: code: 1  signal: null
13 info lifecycle ionic-hello-world@~ionic:serve: Failed to exec ionic:serve script
14 verbose stack Error: ionic-hello-world@ ionic:serve: `ionic-app-scripts serve "--v2" "--runLivereload" "--isPlatformServe" "--livereload" "--port" "8100" "--livereload-port" "35729" "--address" "192.168.1.7" "--iscordovaserve" "--nobrowser"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid ionic-hello-world@
16 verbose cwd /Users/faisalfarooq/Desktop/the_internet/ResSeniorIonic
17 error Darwin 16.4.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ionic:serve" "--" "--v2" "--runLivereload" "--isPlatformServe" "--livereload" "--port" "8100" "--livereload-port" "35729" "--address" "192.168.1.7" "--iscordovaserve" "--nobrowser"
19 error node v4.4.2
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error ionic-hello-world@ ionic:serve: `ionic-app-scripts serve "--v2" "--runLivereload" "--isPlatformServe" "--livereload" "--port" "8100" "--livereload-port" "35729" "--address" "192.168.1.7" "--iscordovaserve" "--nobrowser"`
22 error Exit status 1
23 error Failed at the ionic-hello-world@ ionic:serve script 'ionic-app-scripts serve "--v2" "--runLivereload" "--isPlatformServe" "--livereload" "--port" "8100" "--livereload-port" "35729" "--address" "192.168.1.7" "--iscordovaserve" "--nobrowser"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ionic-hello-world package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ionic-app-scripts serve "--v2" "--runLivereload" "--isPlatformServe" "--livereload" "--port" "8100" "--livereload-port" "35729" "--address" "192.168.1.7" "--iscordovaserve" "--nobrowser"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ionic-hello-world
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ionic-hello-world
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
