### ISSUE TITLE
barrels not working on version 0.0.31

### ISSUE THREAD

**Issue by andrevcf** [driftyco/ionic-app-scripts#154] opened 2016-10-13 21:47 UTC
barrels not working on version 0.0.31
with 0.0.30 they are ok

**Comment by mhartington** [comment] 2016-10-14 01:34
Hi, it seems you have not filled our issue form with the correct information that we ask for. Please re-submit your issue again using the form, not just deleting it.

**Comment by Manduro** [comment] 2016-10-14 09:49
I can confirm this issue. Here is an extended description:

#### Short description of the problem:
Watching fails when using a folder path in an import statement, to import from a `index.ts` file. This was working pre 0.0.31. Example:

folder1/file.ts:
```ts
import { something } from '../folder2';
```
folder2/index.ts:
```ts
export function something() {}
```

Quickfix: when importing from `../folder2/index` everything works fine.


```
[11:41:31]  bundle started ... MEM: 257.0MB 
[ DEBUG! ]  entry: /path/to/app/folder/src/app/main.dev.ts, dest: /path/to/app/folder/www/build/main.js, 
            cache: undefined, format: iife MEM: 257.0MB 
[11:41:31]  copy finished in 9.64 s MEM: 257.4MB 
[11:41:34]  lint finished in 11.91 s MEM: 219.3MB 
[ DEBUG! ]  worker resolve, task: lint, pid: 6230 MEM: 219.3MB 
[ DEBUG! ]  worker exited, task: lint, pid: 6230 MEM: 319.6MB 
(node:6229) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Could not resolve '../auth' from /path/to/app/folder/src/state/clients/clients.reducer.ts
```

For the following folder structure:
```
src
- state
-- clients
--- clients.reducer.ts
-- auth
--- index.ts
```

**Which @ionic/app-scripts version are you using?**
0.0.33

**Comment by jgw96** [comment] 2016-10-14 16:15
Hello, thanks! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/166.

**Comment by danbucholtz** [comment] 2016-10-14 16:19
@Manduro,

I'll test this now. Thanks for letting us know.

Thanks,
Dan

**Comment by danbucholtz** [comment] 2016-10-14 16:25
@Manduro,

This is working for me with the latest in master. Let me know if you're still seeing this later today after we release the next version please.  @andrevcf too. Thanks!

Thanks,
Dan

**Comment by JustinPierce** [comment] 2016-10-14 17:09
@danbucholtz I manually brought your changes down to my local copy, but barrels are still failing to compile on dev builds. I still have to use the `index` workaround. On the other hand, I'm at least getting an error message from the build process!

I'll try this again once an actual release goes out, but I just wanted to give a heads up that all might not be well.

**Comment by danbucholtz** [comment] 2016-10-14 17:13
@JustinPierce,

Okay, let me try the dev build. I only did the `ngc` build.  Thanks for the heads up.

Thanks,
Dan

**Comment by JustinPierce** [comment] 2016-10-14 17:15
@danbucholtz Interestingly, all of the issues I've had since `0.0.30` have only affected dev builds (and `ionic serve`, by extension). I think `ngc` is working some magic behind the scenes.

**Comment by danbucholtz** [comment] 2016-10-14 17:38
@JustinPierce, it's not surprising, that's where most of the changes are.

Thanks,
Dan

**Comment by danbucholtz** [comment] 2016-10-14 19:29
We did not get this issue resolved in time for `0.0.34` release in final testing right now.

I've gotta look at it more.

Thanks,
Dan

**Comment by danbucholtz** [comment] 2016-10-15 04:26
@justin,

I think this is resolved [here](https://github.com/driftyco/ionic-app-scripts/commit/4aa01c1b8aa0d43419d6de2b72958e80de18ceef).  Hopefully I didn't miss any test cases. It is working for me locally with forward paths `./some-dir` and back paths `../../some-dir`.

We'll push this out over the weekend sometime. Please let us know if we need to re-open.

Thanks,
Dan

**Closed by danbucholtz** 2016-10-15 04:26 UTC
Labels: bug

**Comment by Manduro** [comment] 2016-10-15 11:13
@danbucholtz Using 0.0.35 this is fixed for my 88 cases where I was using `/index` as a temporary fix, so you didn't miss any cases :). Thanks!

**Comment by JustinPierce** [comment] 2016-10-15 13:59
@danbucholtz I just took out the `/index` workaround for the 349 places where I was using it, and all seems to be well. Great job, and thank you!
