### ISSUE TITLE
not include node_modules/@types in dev build

### ISSUE THREAD

**Issue by izee** [driftyco/ionic-app-scripts#179] opened 2016-10-17 03:23 UTC
I installed `@types/cordova` and `ionic build` works fine.
but `ionic serve` output:

> [11:19:42]  ionic-app-scripts 0.0.36
> [11:19:42]  watch started ...
> [11:19:42]  build dev started ...
> [11:19:42]  clean started ...
> [11:19:42]  clean finished in 1 ms
> [11:19:42]  copy started ...
> [11:19:42]  transpile started ...
> [11:19:43]  lint started ...
> [11:19:45]  lint finished in 2.36 s
> [11:19:47]  typescript: D:/Develop/Project/team.app/src/pages/home/home.ts, line: 89
> 
>             Cannot find name 'cordova'.
>       L88:  handler: ()=> {
>       L89:      cordova.plugins.settings.openSetting("location_source", ()=> {
>       L90:              createAlert.dismiss();
> [11:19:47]  transpile failed
> 
> [11:19:47]  copy finished in 4.88 s
> [11:19:47]  watch ready in 4.98 s
>

**Comment by danbucholtz** [comment] 2016-10-17 14:59
@izee,

Can you make a sample repo showing your problem? I have not seen this behavior in my testing.

Thanks,
Dan

**Comment by ZiFFeL1992** [comment] 2016-10-17 21:55
Maybe... `declare var cordova: any;` after your imports?

**Comment by izee** [comment] 2016-10-18 02:06
@danbucholtz [demo is here](https://github.com/izee/ionic2-build-demo.git)

**Comment by izee** [comment] 2016-10-18 02:11
`ionic build --dev` always build `prod`.
`npm run build --dev` or `ionic serve` will show the issue.

**Comment by jgw96** [comment] 2016-10-27 16:46
Hello, thanks for using Ionic! I unfortunately cannot reproduce this issue with the latest version of app-scripts. Because of this I am going to close this issue for now. I would recommend asking around on our [forum](https://forum.ionicframework.com) for further help.

**Closed by jgw96** 2016-10-27 16:46 UTC

**Comment by izee** [comment] 2016-10-28 01:10
@jgw96 please checkout this [repo](https://github.com/izee/ionic2-build-demo.git), the issue is still exist.

**Comment by viskin** [comment] 2017-02-25 18:28
Can confirm the issue still exists with ionic-cli 2.2.1.
