### ISSUE TITLE
Latest ionic-app-scripts build includes source map in production build

### ISSUE THREAD

**Issue by masimplo** [driftyco/ionic-app-scripts#322] opened 2016-11-07 21:10 UTC
Running `ionic-app-scripts build` produces a source map file. Also `ionic build android` includes this source map file in the apk. This has been resolved in the past for rollup by https://github.com/driftyco/ionic-app-scripts/pull/63, but I am guessing not for the new process using webpack.

**Comment by danbucholtz** [comment] 2016-11-07 22:12
@masimakopoulos,

This is the expected behavior for now. We're going to be re-visiting this in the coming days.

We're thinking we'll want source maps when running `ionic run android/ios`. We want to have a notion of a production/release build the is minified. Right now it is too hard to run and debug on a device.

Thanks,
Dan

**Comment by masimakopoulos** [comment] 2016-11-08 08:21
I understand being able to debug on the device is a higher priority so what you are saying makes sense. I see your latest commits are related to that so I will just hang in there until this gets done. Once you get there please make sure you shout about it so we know to make use of it in our production builds.
Thanks for the great work.

**Comment by pantonis** [comment] 2016-11-09 08:30
@danbucholtz  ionic run android/ios (debugging on a device) is of high importance especially when you have to test camera etc....
Please do let us know when this is fixed. 

Thanks

**Comment by danbucholtz** [comment] 2016-11-10 02:43
@pantonis, right, that's why we are including the source map :-). We will add a `--release` flag or something to build and utilize minification and skip the source map. For general device usage, we want the source map since that is the best way to test cordova stuff.

Thanks,
Dan

**Comment by pantonis** [comment] 2016-11-10 05:06
@danbucholtz so getting source maps when debugging on a device was fixed with the 0.0.42 release?

**Comment by danbucholtz** [comment] 2016-11-10 06:28
@pantonis, no, I don't think it has ever worked. Uglifyjs is messing with the source map and not working correctly. This is something we need to address.

Thanks,
Dan

**Comment by pantonis** [comment] 2016-11-10 06:31
I remember one of the beta versions it worked.

**Closed** 2017-01-06 06:34 UTC

**Comment by pantonis** [comment] 2017-01-06 06:51
Confirmed

**Comment by moldstadt** [comment] 2017-01-19 06:30
@danbucholtz I see this issue has been closed, but how do I build a release apk without the source map?  When I build with `ionic build android --release --prod` I still see the source map in the resulting apk.
```
$ ionic info
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

Your system information:

 You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.4.0

Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v6.9.2
Xcode version: Not installed


******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************
```

**Comment by danbucholtz** [comment] 2017-01-19 07:57
@moldstadt,

That is not the expected behavior so please file a different issue with instructions on how to recreate.

Thanks,
Dan
