### ISSUE TITLE
App-script 0.0.38 mapping typescript not working

### ISSUE THREAD

**Issue by macdasi** [driftyco/ionic-app-scripts#286] opened 2016-10-31 15:46 UTC
open developers tools and sources all in .js 
there is no TS files . 
after I downgraded to 0.0.36 it works .

**Comment by danbucholtz** [comment] 2016-10-31 15:46
@macdasi,

There are `.js` source maps though, right?

We are still working on getting it mapped all the way back to `.ts` files.

Thanks,
Dan

**Comment by jgw96** [comment] 2016-10-31 15:55
Hello, thanks for opening an issue with us. I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/275 but feel free to continue the discussion!

**Closed by jgw96** 2016-10-31 15:55 UTC
