### ISSUE TITLE
Missing source on chrome when debugging on device

### ISSUE THREAD

**Issue by pantonis** [driftyco/ionic-app-scripts#407] opened 2016-11-16 18:15 UTC
#### Short description of the problem:
When I run ionic run android -device and open chrome://inspect I cannot see the src files and it is impossible to debug functions such as camera. I am blocked for a month and cannot proceed.
![capture](https://cloud.githubusercontent.com/assets/3295086/20359598/4cfca174-ac39-11e6-9102-95ad0d74de9d.PNG)

This is what I see.
I have the following snippet in the package.json

````
"config": {
    "ionic_bundler": "webpack",
    "ionic_source_map": "source-map"    
  },
````

#### What behavior are you?
View .ts files and debug

**Which @ionic/app-scripts version are you using?**
0.0.44

**Comment by nalkon** [comment] 2016-11-17 20:53
+1. Same here.

**Comment by danbucholtz** [comment] 2016-11-19 04:25
This is presently the expected behavior. I'm not a huge of fan of it. For now, Use `ionic run android -l`. That should get the maps and a better development set-up.

Thanks,
Dan

**Comment by pantonis** [comment] 2016-11-19 06:02
No man. This does not work as well. No source code even with the ''''ionic run android -l''''

**Comment by m1aw** [comment] 2016-11-21 10:17
Tried to downgrade to @ionic/app-scripts to 0.0.43. Yet the problem still persists.

**Comment by danbucholtz** [comment] 2016-11-21 16:22
A quick fix would be to add the `--dev` option to the`ionic:build` npm script, but that is not a great long term option as it doesn't do ahead-of-time compiling.

We are going to address this.

Thanks,
Dan

**Comment by pantonis** [comment] 2016-11-21 17:00
Thanks @danbucholtz 

I tried what you suggested but still no luck no ts files. I see more files though. Check the screenshot below

![image](https://cloud.githubusercontent.com/assets/3295086/20492273/c391fe10-b01c-11e6-8d7a-12d8d1b17d56.png)

**Comment by meeximum** [comment] 2016-11-21 20:36
+1

**Comment by nalkon** [comment] 2016-11-23 23:18
Ionic Team, please fix it ASAP. It's absolutely impossible to work effectively when you can't debug on device. It takes hours to figure out things that usually takes minutes if you have a debugger. And there are features that you can troubleshoot on devices only, you can't use emulator or browser. It's showstopper for final release. Seriously.

**Comment by pantonis** [comment] 2016-11-25 11:16
Any news on this one?

**Comment by julianlecalvez** [comment] 2016-11-25 15:49
+1 !

**Comment by ekrapfl** [comment] 2016-11-29 18:32
+1

**Comment by pantonis** [comment] 2016-12-02 17:27
Guys. Regarding the problem. 

```
ionic run android -l
```

does the job for now. The ts files are under the build folder. scroll down a lot or just use Ctrl + P and search for .ts. Here is a screenshot.

![capture](https://cloud.githubusercontent.com/assets/3295086/20843769/620c0c38-b8c5-11e6-8e41-459150169b3f.PNG)


Hope this helps for now.

**Comment by pantonis** [comment] 2016-12-02 17:40
:( If you want to debug a cordova plugin you can't if you include the -l flag. Getting an error cordova_not_available

**Comment by pantonis** [comment] 2016-12-02 19:22
Thanks to @victorivens05 I managed to partially solve it

I removed the following

```
"config": {
    "ionic_bundler": "webpack",
    "ionic_source_map": "source-map"    
  },
```

and as Dan suggested I included the --dev flag in the "ionic:build"

This is my packages.json

```
{
  "name": "ionic-hello-world",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "ionic:build": "ionic-app-scripts build --dev",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "ionic-angular": "2.0.0-rc.3",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26",
    "angular2-moment": "1.0.0-beta.rc.1"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.46",
    "typescript": "2.0.6"
  },  
  "description": "Ion1",
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "cordova-plugin-camera",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": []
}
```

I run ionic run android 
and I can debug

**Comment by danbucholtz** [comment] 2016-12-04 22:09
This will be fixed in the coming days.

Thanks,
Dan

**Comment by danbucholtz** [comment] 2016-12-19 17:09
Hi all,

This is resolved in `0.0.48` which was just published.

Please let me know if you have any issues.

Thanks,
Dan

**Closed by danbucholtz** 2016-12-19 17:09 UTC
Labels: bug

**Comment by pantonis** [comment] 2016-12-23 08:09
No Dan.

I updated to 0.0.48 and it does not work again. Even the workaround solution that you suggested above and it worked does not work now.

:(

**Comment by pantonis** [comment] 2016-12-23 08:34
Actually it only works If I include the -l flag (ionic run android -l). 
If I remove it (ionic run android) I don't see any source files. Dont know if the latter (ionic run android) is a bug. 

For me the -l flag solves the problem!!!

**Comment by meeximum** [comment] 2016-12-23 09:20
maybe there could be an update of the params you can use with run/build command?
--prod, --release, -l 
I can't find a proper list in the docs?

**Comment by coreyroth** [comment] 2016-12-23 14:24
I tried it last night on one of my apps and I can confirm that I can see .ts files again in chrome://inspect without using any special flags.  Remove the android platform and re-add it (if you haven't already).

**Comment by pantonis** [comment] 2016-12-23 17:16
@coreyroth No mate. I have tried what you suggested but it does not show ts files. In any case the -l seems to resolve the issue for now and it is the one that I actually use as I develop.

**Comment by mehrad-rafigh** [comment] 2017-03-03 11:02
When I run `ionic run android -l`, the app gets stuck. When I run `ionic run android --debug`, the app works correctly, but there are no source-maps. Is there a guide on how to this?

**Comment by drewhawken** [comment] 2017-03-09 16:54
@mehrad-rafigh when I run ionic run android --debug -l it seems to work without issues for me.

**Comment by cocowalla** [comment] 2017-07-18 14:46
A few months later, and this is _still_ an issue in 2.0.2. I sense that this is not a priority, but I'm unsure why that would be - having source maps when running in an emulator or on a device is absolutely invaluable.

**Comment by zhzhch335** [comment] 2018-05-28 00:36
I sloved it by **Change My ShadowSocks Mode As PAC Mode** instead of global mode.
I hope it could help you.
Check your browser's proxy.

**Comment by JuanCalderon** [comment] 2018-10-10 16:03
![screen shot 2018-10-10 at 9 38 33 am](https://user-images.githubusercontent.com/4644775/46749706-8b967980-cc73-11e8-9620-a538157e563c.png)

The source code are the orange folders. Instead to use locahost, use the local IP. It works for me.

**Comment by BassamHabash** [comment] 2018-12-16 08:43
Hi , I have the same issue in ionic 4, there is any update for that ?
@danbucholtz

**Comment by alexandruluca** [comment] 2019-06-23 18:50
Same for me. Ionic 3 and 4. Any updates on this?

**Comment by AghaAliAbbasKhan** [comment] 2019-07-11 08:38
Guys i had the same issue, but if we make an ionic cordova run android --aot build instead of --prod then we get to debug the code on real device
