### ISSUE TITLE
Error after updating app script

### ISSUE THREAD

**Issue by sriteja09** [driftyco/ionic-app-scripts#354] opened 2016-11-10 14:10 UTC
sritejas-MacBook-Pro:varanda sriteja$ ionic serve
******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)

******************************************************

TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Object.runr (/usr/local/lib/node_modules/ionic/lib/cli.js:191:19)
    at /usr/local/lib/node_modules/ionic/lib/cli.js:54:9
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Cannot read property 'hasOwnProperty' of undefined (CLI v2.1.7)

Your system information:

Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.7
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.42
ios-deploy version: Not installed
ios-sim version: 5.0.10 
OS: macOS Sierra
Node Version: v6.5.0
Xcode version: Xcode 8.1 Build version 8B62

**Comment by rapropos** [comment] 2016-11-10 21:56
There are [multiple reports of this error](https://forum.ionicframework.com/t/cannot-read-property-hasownproperty-of-undefined/68965) on the forums. I suspect that it's caused by old projects that have no "scripts" stanza in their `package.json`. If that's the case, printing an error message indicating that should solve this.

**Comment by sriteja09** [comment] 2016-11-11 05:13
Thanks for the reply ,

 Yes its an old project with ionic 1. but it should not prompt an error while running .any steps to solve this

**Comment by jthoms1** [comment] 2016-11-14 23:57
This is has been resolved with CLI release 2.1.8. Thank you!

**Closed by jthoms1** 2016-11-14 23:57 UTC
