### ISSUE TITLE
pipe in template cause ionic build failure @2.0RC

### ISSUE THREAD

**Issue by lwz7512** [driftyco/ionic-app-scripts#150] opened 2016-10-13 10:38 UTC
Hi dear, I package my project using ionic build android,  but it failed and report:

```
mobile/kiscp/.tmp/pages/home/home.ngfactory.ts:1455:72: Supplied parameters do not match any signature of call target.
```
the error line metioned by console is:
```
const currVal_6:any = import4.interpolate(1,'',valUnwrapper.unwrap(import4.castByValue(this._pipe_relativeTime_0_0,(<_View_HomePage0>this.parent)._pipe_relativeTime_0.transform)(this.context.$implicit.ctime)),'');
```

After narrow down the problem, I found its caused by pipe in template!

my template clip include the pipe is:
```
<ion-col text-right class="gray-color">{{weibo.ctime | relativeTime}}</ion-col>
```

here present my relative time calculate pipe component:
```
import { Injectable, Pipe } from '@angular/core';

/*
  Generated class for the RelativeTime pipe.

  See https://angular.io/docs/ts/latest/guide/pipes.html for more info on
  Angular 2 Pipes.
*/
@Pipe({
  name: 'relativeTime'
})
@Injectable()
export class RelativeTime {
  /*
    Takes a value and makes it lowercase.
   */
  transform(value: string, args: any[]) {
    // value = value + ''; // make sure it's a string
    if(!value) return 'NO_TIME';

    let milisecond = parseInt(value)*1000;
    return this.timeDifference(new Date(), new Date(milisecond));
    // return value.toLowerCase();
  }

  /**
   * 相对时间长度
   * @param  {date} current  当前时间
   * @param  {date} previous 历史时间
   * @return {string}        相对时间长度
   */
  timeDifference(current, previous):string {

    var msPerMinute = 60 * 1000;
    var msPerHour = msPerMinute * 60;
    var msPerDay = msPerHour * 24;
    var msPerMonth = msPerDay * 30;
    var msPerYear = msPerDay * 365;

    var elapsed = current - previous;

    if (elapsed < msPerMinute) {
      if(Math.round(elapsed/1000)<3) return '刚刚';
      return Math.round(elapsed/1000) + ' 秒前';
    }

    else if (elapsed < msPerHour) {
      return Math.round(elapsed/msPerMinute) + ' 分前';
    }

    else if (elapsed < msPerDay ) {
      return Math.round(elapsed/msPerHour ) + ' 小时前';
    }

    else if (elapsed < msPerMonth) {
      return '大约 ' + Math.round(elapsed/msPerDay) + ' 天前';
    }

    else if (elapsed < msPerYear) {
      return '大约 ' + Math.round(elapsed/msPerMonth) + ' 月前';
    }

    else {
      return '大约 ' + Math.round(elapsed/msPerYear ) + ' 年前';
    }
  }

}

```

also, development process is works while running in dev mode, but failed in build...

**Comment by ezekjh** [comment] 2016-10-13 17:57
Any updates on this? I'm experiencing this exact same issue.

**Comment by ezekjh** [comment] 2016-10-13 18:22
Ok, I narrowed it down to this:  args: any[]
Removing args from the declaration does it.
Is this a bug or an intended behavior?

**Comment by danbucholtz** [comment] 2016-10-13 20:40
@ezekjh,

This is how Angular `ngc` works. It is very strict with `types` for params, variables, etc.

Please let me know if I can help with anything else. I'm going to close this for now since this is the expected Angular behavior.

Thanks,
Dan

**Closed by danbucholtz** 2016-10-13 20:40 UTC

**Comment by adamdbradley** [comment] 2016-10-13 20:43
@ezekjh Would you be able to raise this issue with angular? For production builds, we're just spawning the `ngc` command and do not have control of what happens after that.

**Comment by ezekjh** [comment] 2016-10-13 20:47
@danbucholtz yes, I figured it now since I was getting lots of errors due to parameters. This one was a little bit trickier.. 
@adamdbradley I not sure if this is an issue, I think we may have put the "args[]" there just by following an example.. But looking at recent angular documentation I don't see that pattern there..
