### ISSUE TITLE
[uglifyjs] Error: SyntaxError: Unexpected token: punc ([)

### ISSUE THREAD

**Issue by jasonwaters** [driftyco/ionic-app-scripts#206] opened 2016-10-20 16:47 UTC
I recently upgraded from `0.0.30` to `0.0.36`.  On `0.0.30` my build works fine, but after updating I get this error when I run `ionic serve` or `npm run build`:

```bash
[10:44:11]  sass started ...
[10:44:13]  uglifyjs failed: SyntaxError: Unexpected token: punc ([)
[10:44:13]  ionic-app-script task: "build"
[10:44:13]  Error: SyntaxError: Unexpected token: punc ([)
```

based on the error, I assumed it was something wrong in my js, but that doesn't make sense since the only thing I changed is the version number for ionic-app-scripts...

Any ideas?

**Comment by danbucholtz** [comment] 2016-10-20 16:50
@jasonwaters,

It is likely something wrong with the transpilation or bundling process.

What does your `tsconfig.json` look like? Can you make a sample repo that we can recreate the issue on?

Thanks,
Dan

**Comment by jasonwaters** [comment] 2016-10-20 16:54
here's my tsconfig:

```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "target": "es5",
    "types": ["node", "hammerjs", "phonegap", "jasmine", "handlebars"],
    "baseUrl": ".",
    "paths": {
      "humanize-duration": ["node_modules/humanize-duration/humanize-duration.js"]
    }
  },
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```

my project is pretty big, so I'm not sure what to extract to duplicate the problem in a smaller sample repo.  Any way I could debug t some how to find out what that error is actually referring to?

**Comment by jgw96** [comment] 2016-10-26 15:14
Hello @jasonwaters , sorry for the delay on this! Would you mind updating to the latest beta release of app-scripts (`npm install @ionic/app-scripts@beta --save-dev`) and trying again? Thanks! This release uses webpack by default and includes alot of bug fixes and perf improvements. Thanks!

**Comment by jgw96** [comment] 2016-10-28 12:45
Hello! I am going to be closing this one as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/239. Thanks!

**Closed by jgw96** 2016-10-28 12:45 UTC
Labels: needs_reply
