### ISSUE TITLE
Ionic App Script Clean not working for me

### ISSUE THREAD

**Issue by nottinhill** [driftyco/ionic-app-scripts#230] opened 2016-10-24 15:53 UTC
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:

This line in package.json:
`"clean": "ionic-app-scripts clean",`
should clean the whole www directory. However it doesn't-

#### What behavior are you expecting?

To have www directory completely cleaned out when saying

`ionic build`

**Steps to reproduce:**
1. Enter `"clean": "ionic-app-scripts clean"`
2. Enter `ionic build` in Terminal 
3. Watch www cleans not completely out.

**Which @ionic/app-scripts version are you using?**

0.0.36

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by jgw96** [comment] 2016-10-24 16:27
Hello, thanks for using Ionic! This is actually expected behavior which was just recently introduced. We now only clear out the build folder instead of erasing the www folder. Since this is expected behavior I am going to close this issue for now, but if you could comment on your use case for clearing out the entire www folder that would be awesome!

**Closed by jgw96** 2016-10-24 16:27 UTC

**Comment by nottinhill** [comment] 2016-10-24 20:01
We have configurations and images that do change in assets folder. If we change these in `src/assets` folder, they do not copied over to `www/assets/config/myConfig.json`for example.

**Comment by nottinhill** [comment] 2016-10-25 11:48
Copy task is not overriding old files. Please investigate.

**Comment by nottinhill** [comment] 2016-10-25 12:18
This is the only way we got it to work. This is a node_modules file. I think this is not what anybody does want.

http://imgur.com/a/CKea3
