### ISSUE TITLE
[0.0.42] no longer supported by proxies list of ionic.config.json

### ISSUE THREAD

**Issue by konrin** [driftyco/ionic-app-scripts#346] opened 2016-11-10 06:50 UTC
#### Short description of the problem:
Stopped working proxy list of ionic.config.json. In consequence of this, stopped working xhr the application.

#### What behavior are you expecting?
Working proxy list of ionic.config.json.

**Which @ionic/app-scripts version are you using?**
0.0.42

Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.7
Ionic App Lib Version: 2.1.4
ios-deploy version: 1.9.0 
ios-sim version: 5.0.10 
OS: macOS Sierra
Node Version: v7.0.0
Xcode version: Xcode 8.1 Build version 8B62

**Comment by peterpeterparker** [comment] 2016-11-10 11:45
Same here!

    GET http://localhost:8100/....404 (Not Found)

**Comment by MELAS007** [comment] 2016-11-10 14:55
SAme here!

ionic serve --l doesn't work!

**Comment by Manduro** [comment] 2016-11-10 15:02
Working for me, but it's not for a co-worker using the very same project and up to date dependencies.

**Comment by MELAS007** [comment] 2016-11-10 15:09
How did you do?

**Comment by cambieri** [comment] 2016-11-12 12:10
I'm using ionic-app-scripts version 0.0.43 and it seems to me that the problem appears only when there is more then one entry in the "proxies" array (ionic.config.json file). In that case, only the first entry works correctly, while the others are ignored.
Am I right? Will it takes long to fix this bug?
Thanks for the great work.

**Comment by jthoms1** [comment] 2016-11-14 17:18
Proxies should be supported in the latest release of ionic-app-scripts.  I was unaware of the issue with it only using the first entry.  I will test this out and provide my results today.  Thanks!

**Comment by cambieri** [comment] 2016-11-15 10:29
I'm very glad to help. Have you found the bug?
Please let me know if I can be of any further help.

**Comment by cambieri** [comment] 2016-11-16 08:34
I can confirm that the fix proposed by vaskou works perfectly.
Will it be merged in the next release?
Thanks.

**Comment by cambieri** [comment] 2016-11-18 07:45
Any news about this? The fix is still not presente in version 0.0.45.
Is it possible to merge the vaskou fix in the next release?
Thanks.

**Comment by jthoms1** [comment] 2016-11-18 23:10
Looks like @vaskou fix was merged.  I will close this once it is released.

**Comment by cambieri** [comment] 2016-11-19 07:52
Great news! Thank you.
Greetings.

**Comment by peterpeterparker** [comment] 2016-11-22 06:48
Solved in 0.0.46, thx a lot @jthoms1 !

**Closed** 2016-12-21 13:58 UTC
