### ISSUE TITLE
CALL_AND_RETRY_LAST allocation failed

### ISSUE THREAD

**Issue by sfabriece** [driftyco/ionic-app-scripts#65] opened 2016-10-02 19:32 UTC
I'm migrating to rc0 and using app-scripts version 0.0.27 
with the latest ionic-cli: ionic@2.1.0

After a while running ionic serve i get the following output:

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

npm
 ERR! Windows_NT 10.0.10586
npm
 ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch"

npm
 ERR!
 node v6.6.0

npm ERR! npm
 v3.10.8
npm ERR! code
 ELIFECYCLE
npm ERR!
 perkd@ watch: `ionic-app-scripts watch`
npm ERR! Exit status 3

npm ERR!

```

**Comment by jgw96** [comment] 2016-10-03 14:11
Hello, thanks for using Ionic. I am going to be closing this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/62. Thanks!

**Closed by jgw96** 2016-10-03 14:11 UTC
