### ISSUE TITLE
Live Reload CSS Windows 10

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic-app-scripts#518] opened 2016-12-07 21:55 UTC
When I was changing about page banner color in conference app testing, I did not see the css update automatically as I would expect. It did not work how it works on most browsers.

Thanks,
Dan

**Comment by dejancencelj** [comment] 2016-12-08 05:40
CSS reload doesn't work for some time now :/

**Comment by jthoms1** [comment] 2016-12-09 15:09
@dejancencelj Can you provide the output when you run `ionic info` from within the project? Thank you!

**Comment by dejancencelj** [comment] 2016-12-09 15:29
Ionic Framework Version: 2.0.0-rc.3-201611211919
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.46
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed

**Comment by jthoms1** [comment] 2016-12-12 19:34
The issue is because livereload.js was inserted using "http://0.0.0.0:8100" instead of "http://localhost:8100". This has been resolved in the nightlys and will be fixed in release 0.0.47. I verified on Windows 7 with Chrome.

**Closed by jthoms1** 2016-12-12 19:34 UTC
