### ISSUE TITLE
[Bug] Barrel not working, fails silent

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic-app-scripts#234] opened 2016-10-24 21:41 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Ok so i have some barrels setup in one folder, it was working before i updated to RC.1 and `@ionic/app-scripts`, however when i updated errors started popping out saying:

![image](https://cloud.githubusercontent.com/assets/9698639/19665846/b5685904-9a0c-11e6-89c8-0215d484f4ef.png)

Where the 3 question marks are placed, those are the ones coming from that specific barrel, i'm aware that order matters when those providers depends on each other, so the ones without any deps on other providers goes up in the file, while the ones that depends on other providers has to go after each of their providers dependencies.

Maybe it's not `@ionic/app-scripts` but `ionic-angular` the one has this issue so i'm making a copy of this issue in their repo: https://github.com/driftyco/ionic/issues/8884
</span>

<span is-issue-template></span>

**Comment by Luchillo** [comment] 2016-10-25 16:46
There's a few other silent errors, this error is different but still the cli doesn't show webpack errors but i managed to show one just using the `webpack-build-notifier` plugin:
![image](https://cloud.githubusercontent.com/assets/9698639/19691989/e32b2288-9a9b-11e6-942d-6f468365483f.png)

**Comment by jgw96** [comment] 2016-10-25 19:56
Hello, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/189.

**Closed by jgw96** 2016-10-25 19:56 UTC

**Comment by Luchillo** [comment] 2016-10-25 20:06
I'm not sure if they're the same, his case is when using `ionic run android` while mine fails right from start with `ionic serve` which for him it works.

**Comment by Luchillo** [comment] 2016-10-25 20:11
Also his output states an error while mine only shows error in the browser, thats why i say it fails silent.
