### ISSUE TITLE
import problem with the new bundler (rollup)

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-app-scripts#390] opened 2016-11-14 16:04 UTC
_From @nickwinger on November 11, 2016 14:51_

Somehow Webpack messes up my code which was working with beta11.
It seems that it can't handle circular dependencies: https://github.com/webpack/webpack/issues/1788
I'm guessing this is the problem with my app, as sometimes an import just returns undefined.
I still cannot upgrade to RC2 and stick with beta11.
Somehow i wonder if i will ever be able to upgrade to a RC Version.
Why not stick with browserify, everything was working fine...

Update:
It is really related to WebPack having problems with circular imports. (which have nothing to do with angular circular dependencies at runtime).
But it is a problem for my app and the way Ionic also works, here's the problem:
I have a ActionCommands service that is used by many pages to execute common actions.
Inside the ActionCommands service i also have to include several pages for modals etc. to be opened upon triggering an action.
However these pages need again the ActionsCommands service to trigger further actions.
Here's is the circularity with importing.
BUT: There is no circularity with runtime dependencies, because the Pages imported inside the ActionsCommands service are only used to create a modal out of it.

Solution needed:
Lazy import / create a modal from a page.
OR
Create a modal by a string e.g. the name of the page, so the page does not have to get imported (by webpack)

What are the suggestions. I guess this will be a huge problem. I have read the angular 2 router has some kind of lazy loading modules.

_Copied from original issue: driftyco/ionic#9123_

**Comment by danbucholtz** [comment] 2016-11-14 16:08
@nickwinger,

I'd need to see an example as this is pretty vague. ES2015 imports are static and Typescript should validate the imports so I am confused why you'd ever be importing/exporting null, etc.

This doesn't seem to be an issue with the build process as much as your code. Please create a simple example and we'll take a look.

Thanks,
Dan

**Comment by nickwinger** [comment] 2016-11-15 05:44
Hi Dan,

i will create an example, where should i upload it ?
It's not a problem with "your" build process and not with Typescript.
It has been working with beta.11 browserify and SystemJS.
It's a problem with webpack and ES2015 module system as you cannot lazy import
js-files like with require (in nodeJS). Therefore circular ES2015-imports are not working
with webpack (at runtime).

I will create a simple example. (and show the "ugly" workaround i'm currently doing)

Thx

**Comment by danbucholtz** [comment] 2016-11-15 16:36
@nickwinger,

Correct, `commonjs` require is very dynamic. `es2015` imports are not by design. You may have to take a different technical approach. If you upload a repo to simple sample repo to Github, we can take a quick look.

Thanks,
Dan

**Comment by nickwinger** [comment] 2016-11-19 12:20
Hi Dan,

i have created a repo to demo the issue:
https://github.com/nickwinger/webpackImportProblem

The app is broken (you can see an error in the console, "Can't resolve all parameters for LoginPage")

Have a look at the commands.ts file. There you can commend/uncommend lines to make the app work with lazy require/import.

I have created a simple example for login/register, but the idea is that in the commands file is more logic for certain tasks that you need multiple times in different pages, so the idea is to have that logic in one place. That's were the trouble with webpack imports start (circularity).
Note that browserify and System.js don't have that problem as the import mechanism is different there (and better in my opinion).

I have made a workaround, lazy requiering the pages via string token, maybe that's a way to go for the modalController create function to avoid the webpack problems.

**Comment by danbucholtz** [comment] 2017-01-28 05:26
Hello,

I think resolving this issue is outside of the scope of app-scripts right now. It seems like it's a rollup or webpack issue. Sorry, but this is off our radar at this time.

Thanks,
Dan

**Closed by danbucholtz** 2017-01-28 05:26 UTC
Labels: needs_reply
