### ISSUE TITLE
Live Reload not working with .39 ionic run failing completely with .42

### ISSUE THREAD

**Issue by DhruvGupta5** [driftyco/ionic-app-scripts#352] opened 2016-11-10 12:37 UTC
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
Ionic LiveReload not working, have to quit and start ionic run everytime need to check changes.

#### What behavior are you expecting?
live reload to work whenever any of the changes are made to the app

**Steps to reproduce:**
1. ionic run android -l -c
2.
3.

```
insert any relevant code between the above and below backticks
```
  "scripts": {
    "build": "ionic-app-scripts build --dev",
    "watch": "ionic-app-scripts watch",
    "serve:before": "watch",
    "emulate:before": "build",
    "deploy:before": "build",
    "build:before": "build",
    "run:before": "build"}

**Which @ionic/app-scripts version are you using?**
.39 but tested with newer one also

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by danielabbatt** [comment] 2016-11-10 15:58
ionic run android -lc also not reloading, using standard webpack build on .42 with updated cli:

```
Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.7
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.42
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by jthoms1** [comment] 2016-11-14 17:46
There currently are issues with `emulate` and `run` livereloading. I should have this resolved by end of day. I will keep this thread informed when the release 2.1.9 of CLI occurs which will contain the fix.  Thank you for reporting this and your patience.

**Comment by jthoms1** [comment] 2016-11-18 23:01
We released a more recent CLI that fixes these issues.  Please ensure to install 2.1.12.

`npm install -g ionic@latest`

**Closed by jthoms1** 2016-11-18 23:01 UTC

**Comment by DhruvGupta5** [comment] 2016-11-20 15:14
livereload works its still bit buggy on ts file changes updates, but that can be managed, the worst part all the server and console logs are gone upon ionic android run -l -c -s, can you point out what to do, its extremely annoying

**Comment by mburger81** [comment] 2016-12-05 15:50
@jthoms1 when do you think you will resolve the log issue? It's incredible difficult to develop without this, with version 2.1.8 console log works, but as described in this log the live-reload does not work.
So you have to chose using live reload or console.log but this is very very difficult and hard to develop.

**Comment by DhruvGupta5** [comment] 2016-12-05 16:53
@mburger81 if you are using vscode you can use cordova extension to view the logs additionally see https://github.com/driftyco/ionic-app-scripts/pull/492#issuecomment-264735590 to get liveReload to work

**Comment by DhruvGupta5** [comment] 2016-12-05 16:55
@mburger81 its a temporary fix by @pelzerim but works fine

**Comment by mburger81** [comment] 2016-12-06 09:13
@DhruvGupta5 thx for the link
the problem is, 

using ionic cli 2.1.14 with @ionic/app-script 0.0.46 livereload is working out of the box. So the problem is not livereload in my opinion. 
My problem is, the console log doesn't work anymore!
