### ISSUE TITLE
Importing jsnlog does not seem to work

### ISSUE THREAD

**Issue by masimakopoulos** [driftyco/ionic-app-scripts#227] opened 2016-10-24 12:24 UTC
I am trying to use [jsnlog](http://js.jsnlog.com/) with RC1 (was using it with Beta11) but I am getting 

> Uncaught TypeError: JL is not a function
    at window.onerror (main.js:53043)

I am importing it like:
`import JL from 'jsnlog';`

Could you please add it to your [examples](https://github.com/danbucholtz/ionic-third-party-lib-mega-test/blob/master/src/app/app.module.ts) @danbucholtz and see if you can get it to work?

**Comment by jgw96** [comment] 2016-10-24 16:23
Hello, thanks for using Ionic! Would you mind installing the latest beta release of app-scripts by running npm install @ionic/app-scripts@beta --save-dev and trying this again? That release uses webpack by default which should handle older commonjs libraries such as this one better out of the box than rollup.

**Comment by jgw96** [comment] 2016-10-24 16:25
Hello, thanks for using Ionic! Since this issue is caused by the same thing as [this issue](https://github.com/driftyco/ionic-app-scripts/issues/225) i am going to close this issue for now.

**Closed by jgw96** 2016-10-24 16:25 UTC
Labels: needs_reply
