### ISSUE TITLE
Ionic2 : Livereload in ios simulator

### ISSUE THREAD

**Issue by jigarsdev** [driftyco/ionic-app-scripts#362] opened 2016-11-11 04:48 UTC
Hello All,

How to do livereload working in ios simulator ? Which command I need to run from command line ? I have tried 

```
ionic emulate ios -l
ionic run ios -l
ionic run ios -l --watch
```

These commands setup the livereload server but on code change nothing happened in ios simulator.

Ionic Info:

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.7
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.42
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: OS X El Capitan
Node Version: v7.0.0
Xcode version: Xcode 8.0 Build version 8A218a
```

**Comment by sveinl** [comment] 2016-11-11 12:45
I dont think livereload on emulator and devices are expected to be working.

I used to do this and that kinda worked.
`ionic emulate ios -l` (Build and installs the app in emulator)
`ionic serve -b` (Starts server)
Then *restart* your app in emulator. If you are lucky that will work :)

**Comment by vjanssens** [comment] 2016-11-11 16:12
I'm currently having the same issue on an actual device (iPhone 7). When I run `ionic run ios --device -l`, the build and the ionic server get started and the app opens. I'm also able to press `r` in the Ionic server to reload the app but after changing a file on my mac the build does not get started and the page does not get reloaded.

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.43
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: macOS Sierra
Node Version: v4.4.7
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by jgw96** [comment] 2016-11-18 17:45
Hello all! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/352. Thanks!

**Closed by jgw96** 2016-11-18 17:45 UTC

**Comment by REPTILEHAUS** [comment] 2016-12-08 18:32
Has anyone got a fix for this yet.. its driving me absolutely bonkers.. when I use emulator flags for console output it says it cant find cordova.. works fine without livereloads flag though

Your system information:

Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v6.7.0
Xcode version: Xcode 8.1 Build version 8B62
