### ISSUE TITLE
app-scripts 1.2.0 build on Linux fails

### ISSUE THREAD

**Issue by pjorquera** [driftyco/ionic-app-scripts#838] opened 2017-03-25 09:07 UTC
#### Short description of the problem:

Build fails when using app-scripts version 1.2.0 on Linux. Output shows a stalled build for more than 10 mins. without any output log. On macOS build is ok.

#### What behavior are you expecting?

Not stalled build.

**Steps to reproduce:**

1. Modify package.json for your app for using app-scripts version 1.2.0
2. Build project using: ionic build [ios | android | browser]
3. Output is stalled after showing the following:

```
ionic-app-scripts build
```

**Which @ionic/app-scripts version are you using?**

1.2.0

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Tested with Linux inside Docker container with the following configuration:

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.9
Node Version: v7.5.0
Xcode version: Not installed
```

**Comment by alexander-alzate** [comment] 2017-03-25 23:28
It doesn't do anything with any command for me, I tried `clean` and `serve` too, but same issue, no output, not any response, but the script seems to be running.

**Comment by danbucholtz** [comment] 2017-03-26 04:27
Hmm. Can you try again in 1.2.1?

Thanks,
Dan

**Comment by pjorquera** [comment] 2017-03-26 09:39
With `1.2.1` builds are still failing in Linux (in macOS everything builds and runs ok).

Now the output log shows the following and then stalls from more than 10 mins.:
```
ionic-app-scripts build "--device" "--prod" "--release"
```

**Comment by rosterrier** [comment] 2017-03-26 10:19
same here with linux and 1.2.1

**Comment by alexander-alzate** [comment] 2017-03-26 18:17
With `1.2.1` `clean` and `run` are still falling for me. There is not any output. *Should I file a new bug?* since this one seems to be fixed on builds, but the problem is quite similar "**app-scripts** does not do anything"

**Comment by evenicoulddoit** [comment] 2017-03-27 11:34
Reverting to 1.1.4 definitely resolved the issue for me, which is consistent with the guys above. Also experiencing no ouptut, Ubuntu 16.04.2, Node v7

**Comment by MT--** [comment] 2017-03-27 16:10
```@ionic/app-scripts@1.2.1 sass <...>/node_modules/@ionic/app-scripts
> node-sass ./src/dev-client/sass/ion-dev.scss --output ./bin/ --output-style compressed```

`No input file was found.`

**Comment by jorrit-wehelp** [comment] 2017-03-27 17:29
Looks like its b4c287a494ded6b151e965e32e3e7cb9373c2f21

In linux we can only use max. 1 arg here, the '=' sign in it makes it just hang here instead of returning an error.
Removing the param from the shebang makes it work for me.

**Comment by danbucholtz** [comment] 2017-03-28 03:03
@jorrit-wehelp,

Wanna do a PR and remove that code?

Thanks,
Dan

**Closed** 2017-03-28 14:28 UTC

**Comment by rosterrier** [comment] 2017-03-28 15:03
still hanging at the same spot

**Comment by TiagoNunesDeveloper** [comment] 2017-03-28 15:15
same here with linux and 1.2.2
