### ISSUE TITLE
Command ionic build android: build failed in Ionic App Scripts 0.0.30

### ISSUE THREAD

**Issue by infinnie** [driftyco/ionic-app-scripts#114] opened 2016-10-07 06:26 UTC
#### Short description of the problem:
When running `ionic serve`, all things work normally and the page gets displayed. However, when I run `ionic build android`, the APK file built would display nothing but a white screen if run. At the same time, when I check the webpage I would find that the style and script files have failed to load.

After all, main.js never gets copied to www\build however many times I try to build it.

I am still wondering what the hell went wrong.

Ionic App Scripts 0.0.23/Ionic 2.0.0 RC 0.

----
Update:
Errors would keep popping up from the console after updating to the latest version 0.0.30. I wonder what I could do. See the comment below.

**Comment by infinnie** [comment] 2016-10-07 08:06
npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle @~prebuild: @
6 silly lifecycle @~prebuild: no script for prebuild, continuing
7 info lifecycle @~build: @
8 verbose lifecycle @~build: unsafe-perm in lifecycle true
9 verbose lifecycle @~build: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;c:\Users\Lemur\SimpleV2App\node_modules\.bin;C:\Program Files\nodejs;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Git\cmd;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Lemur\AppData\Roaming\npm;C:\Users\Lemur\Downloads\android-sdk_r24.4.1-windows\android-sdk-windows\tools;C:\Users\Lemur\Downloads\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools
10 verbose lifecycle @~build: CWD: c:\Users\Lemur\SimpleV2App
11 silly lifecycle @~build: Args: [ '/d /s /c', 'ionic-app-scripts build' ]
12 silly lifecycle @~build: Returned: code: 1  signal: null
13 info lifecycle @~build: Failed to exec build script
14 verbose stack Error: @ build: `ionic-app-scripts build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid @
16 verbose cwd c:\Users\Lemur\SimpleV2App
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v6.3.1
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error @ build: `ionic-app-scripts build`
22 error Exit status 1
23 error Failed at the @ build script 'ionic-app-scripts build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ionic-app-scripts build
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by infinnie** [comment] 2016-10-07 08:17
```
[16:12:22]  Error: Unable to find Angular Compiler "ngc" command: null. Please ensure @angular/compiler-cli has
 been installed with NPM.
```

**Comment by jgw96** [comment] 2016-10-07 13:07
Hello, thanks for opening an issue with us! What version of npm do you have installed? You can check this by typing `npm --version` in your terminal. Thanks!

**Comment by infinnie** [comment] 2016-10-08 04:11
3.10

**Comment by infinnie** [comment] 2016-10-09 00:49
```[08:47:30]  lint finished in 8.51 s                                                                            
[08:47:34]  ngc: TypeError: Cannot read property 'kind' of undefined                                           
    at maybeGetSimpleFunction (C:\Users\Lemur\SimpleV2App\node_modules\@angular\tsc-wrapped\src\collector.js:34
:41)                                                                                                           
    at C:\Users\Lemur\SimpleV2App\node_modules\@angular\tsc-wrapped\src\collector.js:242:41                    
    at visitEachNode (C:\Users\Lemur\SimpleV2App\node_modules\typescript\lib\typescript.js:8251:30)            
    at Object.forEachChild (C:\Users\Lemur\SimpleV2App\node_modules\typescript\lib\typescript.js:8411:24)      
    at MetadataCollector.getMetadata (C:\Users\Lemur\SimpleV2App\node_modules\@angular\tsc-wrapped\src\collecto
r.js:204:12)                                                                                                   
    at ReflectorHost.getMetadataFor (C:\Users\Lemur\SimpleV2App\node_modules\@angular\compiler-cli\src\reflecto
r_host.js:224:43)                                                                                              
    at StaticReflector.getModuleMetadata (C:\Users\Lemur\SimpleV2App\node_modules\@angular\compiler-cli\src\sta
tic_reflector.js:484:40)                                                                                       
    at CodeGenerator.readFileMetadata (C:\Users\Lemur\SimpleV2App\node_modules\@angular\compiler-cli\src\codege
n.js:36:51)                                                                                                    
    at C:\Users\Lemur\SimpleV2App\node_modules\@angular\compiler-cli\src\codegen.js:100:74                     
    at Array.map (native)                                                                                      
                                                                                                               
                                                                                                               
[08:47:34]  ngc: Compilation failed                                                                            
                                                                                                               
                                                                                                               
[08:47:34]  ngc failed:  NGC encountered an error                                                              
                                                                                                               
[08:47:34]  Error: NGC encountered an error
```

@jgw96

**Comment by dmastag** [comment] 2016-10-09 01:03
Do you have any variable called `kind` that you haven't declared yet?

**Comment by infinnie** [comment] 2016-10-09 01:10
@dmastag it’s library code.

**Comment by infinnie** [comment] 2016-10-09 07:17
```
[14:51:11]  lint finished in 7.34 s
[14:51:14]  ngc: TypeError: Cannot read property 'kind' of undefined
    at maybeGetSimpleFunction (C:\Users\Lemur\SimpleV2App\node_modules\@angular\tsc-wrapped\src\collector.js:34:41)
    at C:\Users\Lemur\SimpleV2App\node_modules\@angular\tsc-wrapped\src\collector.js:242:41
    at visitEachNode (C:\Users\Lemur\SimpleV2App\node_modules\typescript\lib\typescript.js:8251:30)
    at Object.forEachChild (C:\Users\Lemur\SimpleV2App\node_modules\typescript\lib\typescript.js:8411:24)
    at MetadataCollector.getMetadata (C:\Users\Lemur\SimpleV2App\node_modules\@angular\tsc-wrapped\src\collector.js:204:12)
    at ReflectorHost.getMetadataFor (C:\Users\Lemur\SimpleV2App\node_modules\@angular\compiler-cli\src\reflector_host.js:224:43)
    at StaticReflector.getModuleMetadata (C:\Users\Lemur\SimpleV2App\node_modules\@angular\compiler-cli\src\static_reflector.js:484:40)
    at CodeGenerator.readFileMetadata (C:\Users\Lemur\SimpleV2App\node_modules\@angular\compiler-cli\src\codegen.js:36:51)
    at C:\Users\Lemur\SimpleV2App\node_modules\@angular\compiler-cli\src\codegen.js:100:74
    at Array.map (native)
```

**Comment by infinnie** [comment] 2016-10-09 07:23
It still doesn’t work yet… Even after uninstalling and reinstalling `node_modules`… `ionic serve` could work fine, though.

**Comment by infinnie** [comment] 2016-10-10 02:57
@jgw96 help me.

**Comment by infinnie** [comment] 2016-10-10 03:02
With the `--dev` flag on, the only error became
>
```
Error: Error copying "src/assets/" to "www/assets/": Error: EPERM: operation not permitted, 
open 'C:\Users\Lemur\SimpleV2App\www\assets\fonts\ionicons.eot',Error: EPERM: operation not 
permitted, open 'C:\Users\Lemur\SimpleV2App\www\assets\fonts\ionicons.svg',Error: EPERM: operation 
not permitted, open 'C:\Users\Lemur\SimpleV2App\www\assets\fonts\ionicons.ttf',Error: EPERM: 
operation not permitted, open 'C:\Users\Lemur\SimpleV2App\www\assets\fonts\ionicons.woff'
```

which I couldn’t tackle.

**Comment by infinnie** [comment] 2016-10-10 06:40
Finally, if I were to use Cordova to directly build the APK, I would get an error when running like
> Application error
> The connection to the server was unsuccessful. (file:///android_asset/www/index.html)
*even if the webpage is actually loaded*.

**Comment by jgw96** [comment] 2016-10-12 15:04
@infinnie unfortunately I cannot seem to reproduce this issue still. Do you have a repo that i can use to reproduce this issue with?

**Comment by infinnie** [comment] 2016-10-12 23:54
@jgw96 Seems a problem of my own machine. But when file copying fails, what can I do to make the production scripts instead of the development ones packaged into the APK?

**Comment by jgw96** [comment] 2016-10-14 20:56
`ionic run android` will do a prod build to your device. After reviewing this issue it looks as if this issue may be due to a library you are using in your project. Do you have the same issue with a blank starter?

**Comment by jgw96** [comment] 2016-10-18 20:17
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-10-18 20:17 UTC
Labels: needs_reply

**Comment by Chethannp** [comment] 2018-08-11 16:31
![2](https://user-images.githubusercontent.com/7566931/43993915-235c3200-9db2-11e8-800e-f2f832d2f30f.png)

This keeps repeating :(
