### ISSUE TITLE
Ionicons are not copied on serve

### ISSUE THREAD

**Issue by Isigiel** [driftyco/ionic-app-scripts#43] opened 2016-09-29 19:52 UTC
When running `ionic serve` the ionicons are not copied into the assets folder.
The `copy` task works and also copies the fonts, but apparently they are missing if called with serve.
I tried all this on a freshly started ionic `--v2` app

I'd be happy to provide more information in case you need it.

_edit_ here's my info http://i.imgur.com/efXoE3q.png
The OS is actually win10

**Comment by jgw96** [comment] 2016-10-03 16:41
Hello! Thanks for opening an issue with us! I am not able to reproduce this issue locally. Would you mind sharing a repo that i can use to reproduce this issue? Thanks!

**Comment by joshgarwood** [comment] 2016-10-03 20:27
This is happening in the ionic-conference-app if you start with a clean clone, it will happen intermittently.

**Comment by jgw96** [comment] 2016-10-05 21:16
@joshgarwood are you also on windows?

**Comment by joshgarwood** [comment] 2016-10-05 21:46
Yes, I am on windows 10.

Thanks!

**Comment by TomDemulierChevret** [comment] 2016-10-06 09:02
I have experienced the same issue intermittently, both with `ionic serve` & `ionic run/build`.

ionic info :

> Cordova CLI: 6.3.1
> Gulp version:  CLI version 3.9.1
> Gulp local:
> Ionic Framework Version: 2.0.0-rc.0
> Ionic CLI Version: 2.1.0
> Ionic App Lib Version: 2.1.0-beta.1
> OS: Windows 7 SP1
> Node Version: v6.7.0
>

**Comment by jgw96** [comment] 2016-10-21 12:43
Hello all! Would you all mind updating to the latest beta release of app-scripts (`npm install @ionic/app-scripts@beta`) and seeing if this is still an issue?

**Comment by joshgarwood** [comment] 2016-10-21 14:47
Hey @jgw96 I just got the latest and am getting an error on build :/  It may be something I'm doing wrong (or need to update), but i get the error shown below

![image](https://cloud.githubusercontent.com/assets/1417324/19602583/b3d5e7ac-977b-11e6-9450-fdfebe221c6c.png)

**Comment by jgw96** [comment] 2016-10-21 14:55
@joshgarwood thanks for the info! Hmm that looks like its pointing to an error in your code, but we are not printing out the error correctly. I will look into this.

**Comment by jgw96** [comment] 2016-10-21 15:07
@joshgarwood unfortunately I am not able to reproduce the above error. Are you using a custom webpack config?

**Comment by joshgarwood** [comment] 2016-10-21 15:09
hmm... i'm not.  I haven't made any adjustments to any of my build configs.  I am on rc1 if that helps.   For what it's worth, this was working before installing the latest ionic-app-scripts.  I'll look a bit more closely on my end too to see if I've possibly missed something.

**Comment by jgw96** [comment] 2016-10-21 19:52
@joshgarwood Sorry for the delay, Github has been down for me because of the huge DNS ddos attack going on today. Could you remove your `node_modules`, make sure your package.json looks like the one [here](https://github.com/driftyco/ionic2-app-base/blob/master/package.json) and then run `npm install` and try again?

**Comment by joshgarwood** [comment] 2016-10-21 22:42
Hey @jgw96 no worries; dns issues has everyone struggling today, ha. So I just follwed your instructions above and am still not seeing the Roboto font :(  It's showing as having ionic-app-scripts version 36 installed, so I'm not sure if that's the right version i should be testing with (because installing with the @beta qualifier installed version 37).  Does that make sense?  I feel like I'm missing something, ha.

**Comment by joshgarwood** [comment] 2016-10-26 01:38
Any updates here?  Still an issue with the latest app scripts :)

**Comment by PabloFNK** [comment] 2016-10-26 08:57
This is happening to us too after update our app from beta11 to rc0.

**Comment by jgw96** [comment] 2016-10-28 15:18
Hello all! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/73.

**Closed by jgw96** 2016-10-28 15:18 UTC
Labels: bug, needs_reply
