### ISSUE TITLE
TypeError: Cannot read property 'AssetUrl' of undefined.

### ISSUE THREAD

**Issue by kleeb** [driftyco/ionic-app-scripts#215] opened 2016-10-21 18:21 UTC
After today's Ionic lib update I cannot build the project anymore.
During production build I am getting:

```
node_modules/@angular/compiler-cli/src/private_import_compiler.js:10 
exports.AssetUrl = compiler_1.__compiler_private__.AssetUrl; 
TypeError: Cannot read property 'AssetUrl' of undefined 
ngc failed 
ionic-app-script task: "build" 
Error: Error 
```

I am also getting plenty of warnings during ionic serve, however the bundle runs (not minified)

```
rollup: Conflicting namespaces: node_modules/@angular/compiler/index.js 
            re-exports 'TextAst' from both node_modules/@angular/compiler/src/template_parser/template_ast.js 
            (will be ignored) and node_modules/@angular/compiler/src/template_parser/template_ast.js.
```

the same result for Ionic App Scripts Version: 0.0.37 and 0.0.36

```
Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
Node Version: v6.2.1
```

**Comment by jgw96** [comment] 2016-10-21 19:50
Hello! Can you make sure that your package.json matches the one here and then remove node_modules and run npm install? Thanks!

**Comment by jgw96** [comment] 2016-10-21 20:19
Hello, I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/212. Thanks!

**Closed** 2016-10-21 20:19 UTC
Labels: needs_reply
