### ISSUE TITLE
Ionic 2 RC.2: build error Cannot find module

### ISSUE THREAD

**Issue by aspidvip** [driftyco/ionic-app-scripts#391] opened 2016-11-14 22:45 UTC
**Hello!**

**file add.html**
```
<input class="input_type_text" [(ngModel)]="auto" placeholder="0" type="number">
```
**IONIC SERVE - is Ok!**

**IONIC BUILD - error** ->
```
Your environment has been set up for using Node.js 6.7.0 (ia32) and npm.

C:\..............\proba>ionic build android

> Proba@ ionic:build C:\Users\Admin.MFC\Desktop\proba
> ionic-app-scripts build

[08:34:31]  ionic-app-scripts 0.0.43
[08:34:31]  build prod started ...
[08:34:31]  clean started ...
[08:34:31]  clean finished in 23 ms
[08:34:31]  copy started ...
[08:34:31]  ngc started ...
[08:34:38]  copy finished in 7.19 s
[08:37:14]  Error: Error at
            C:/Users/Admin.MFC/Desktop/proba/.tmp/pages/myrayon/obay/add_
/gn/add_.ngfactory.ts:82:27
[08:37:14]  Cannot find module
            '../../../../../node_modules/@angular/forms/src/directives/number_va
lue_accessor.ngfactory'.
[08:37:14]  ngc failed
[08:37:14]  ionic-app-script task: "build"
[08:37:14]  Error: Error

npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Admin.MFC\\AppDa
ta\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:build" "--"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! Proba@ ionic:build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Proba@ ionic:build script 'ionic-app-scripts build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Publikun package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Publikun
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Proba
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Admin.MFC\Desktop\proba\npm-debug.log

C:\Users\Admin.MFC\Desktop\proba>
```
**and**
**change file add.html** ->
```
<input class="input_type_text" [(ngModel)]="auto" placeholder="0">
```

**BUILD - OK**

**Comment by rapropos** [comment] 2016-11-14 22:50
I think this is a dupe of #311.

**Comment by jgw96** [comment] 2016-11-18 17:37
Hello all! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/311. Thanks!

**Closed by jgw96** 2016-11-18 17:37 UTC
