### ISSUE TITLE
webpack with Multiple entry points , filePath.replace is not a function

### ISSUE THREAD

**Issue by mashaly100200** [driftyco/ionic-app-scripts#328] opened 2016-11-08 09:27 UTC
i use @ionic/app-scripts   0.0.39

when i use custom webpack.config.js with multi entry point it give me an error

"build dev failed: filePath.replace is not a function"

filePath.replace is in the function named "replacePathVars"  in the file 

node_modules/@ionic/app-scripts/dist/util/config.js

the function "replacePathVars"  use "filePath"  variable as string but with my multi entry point it is a json object

**Comment by mashaly100200** [comment] 2016-11-08 11:55
this is my webpack.config.js file

 ```

var path = require('path');
var webpack = require("webpack");

module.exports = {
  //root: path.resolve('/'),
  devtool: 'source-map', 
  entry: {

    libs:[
      // path.normalize('es6-shim/es6-shim.min'),
      'reflect-metadata',
      path.normalize('zone.js/dist/zone'),
      'ionic-angular',
      'rxjs' 
    ],
    app: path.resolve('src/app/main.dev.ts')  ,

  },
  output: {
    path: path.resolve('www/build/js'),
    filename: 'app.bundle.js',
    pathinfo: false // show module paths in the bundle, handy for debugging
  },
  plugins:[

    new webpack.optimize.UglifyJsPlugin({
      // mangle: {
      //   except: ['$super', '$', 'exports', 'require']
      // },
      sourceMap: true,
      mangle:false,
      output: {
        comments: false
      },
      compress: {
        warnings: false
      }

    }),
    new webpack.optimize.CommonsChunkPlugin({ name: 'libs', filename: 'libs.bundle.js', minChunks: Infinity }),
    // new webpack.optimize.CommonsChunkPlugin({ name: 'app', filename: 'app.js', minChunks: Infinity }),
    // new webpack.optimize.CommonsChunkPlugin({ name: 'common', filename: 'common.js', minChunks: 1, chunks: ['app', 'vendor','app2'] })
  ],
  module: {
    rules: [
      {
        test: /\.ts$/,
        use: 'awesome-typescript-loader',
        options: {
          'doTypeCheck': true
        },
        include: path.resolve('app'),
        exclude: [/node_modules/,
          /platform/]
      },
      // {
      //   test: /\.js$/,
      //   include: path.resolve('node_modules/angular2'),
      //   loader: 'strip-sourcemap'
      // },
      { test: /\.html$/,  loader: 'raw-loader' },
    ],
    noParse: [
      /es6-shim/,
      /reflect-metadata/,
      /zone\.js(\/|\\)dist(\/|\\)zone/
    ]
  },
  externals:{
    //'jquery':true,
    //'$':true,
    // datatables:true
  },
  resolve: {


    alias: {
      // 'angular2': path.resolve('node_modules/angular2')

    },
    extensions: [ '.ts','.js']
  }
};

```

**Comment by danbucholtz** [comment] 2016-11-10 21:55
Duplicate of https://github.com/driftyco/ionic-app-scripts/issues/238. We'll track it there.

Thanks,
Dan

**Closed by danbucholtz** 2016-11-10 21:55 UTC
