### ISSUE TITLE
uglifyjs failed: SyntaxError: Unexpected token: operator (>)

### ISSUE THREAD

**Issue by alamusi** [driftyco/ionic-app-scripts#190] opened 2016-10-17 22:05 UTC
#### Short description of the problem:
when doing ionic build, uglify complains about syntax error. 
> uglifyjs failed: SyntaxError: Unexpected token: operator (>) 

tracing back, i found the generated www/build/main.js file keeps the operator (>) from main.prod.ts as part of the build instead of the main.prod.js file in the ./tmp folder. suspect if it is ngc related, because ionic serve (with transpile) does generate the appropriate main.js file without operator (>)

src/main.prod.ts file is as follows:
```
import { platformBrowser } from '@angular/platform-browser';
import { enableProdMode } from '@angular/core';

import { AppModuleNgFactory } from './app.module.ngfactory';

import { init } from './impl/parse';

// parse init
init();

//config
console.log('ParseUtil config refresh started...');
Parse.Config.get().then(config=>{
  console.log('ParseUtil config refresh completed.');
  enableProdMode();
  platformBrowser().bootstrapModuleFactory(AppModuleNgFactory);
},error=>{
  if (error.code == 209) {
    // invalid session token
    alert('USER SESSION ERROR! Please try again later!');
    Parse.User.logOut();
  } else {
    alert('SERVICE CONNECTION ERROR! Please try again later!');
  }
});
```
./tmp/app/main.prod.js file is as follows **(without > operator)**:
```
import { platformBrowser } from '@angular/platform-browser';
import { enableProdMode } from '@angular/core';
import { AppModuleNgFactory } from './app.module.ngfactory';
import { init } from './impl/parse';
// parse init
init();
//config
console.log('ParseUtil config refresh started...');
Parse.Config.get().then(function (config) {
    console.log('ParseUtil config refresh completed.');
    enableProdMode();
    platformBrowser().bootstrapModuleFactory(AppModuleNgFactory);
}, function (error) {
    if (error.code == 209) {
        // invalid session token
        alert('USER SESSION ERROR! Please try again later!');
        Parse.User.logOut();
    }
    else {
        alert('SERVICE CONNECTION ERROR! Please try again later!');
    }
});
```
www/build/main.js is as follows **(with the > operator)**:
```
var AppModuleNgFactory = new NgModuleFactory(AppModuleInjector, AppModule);

// parse init
init();

//config
console.log('ParseUtil config refresh started...');
Parse.Config.get().then(config=>{
  console.log('ParseUtil config refresh completed.');
  enableProdMode();
  platformBrowser().bootstrapModuleFactory(AppModuleNgFactory);
},error=>{
  if (error.code == 209) {
    // invalid session token
    alert('USER SESSION ERROR! Please try again later!');
    Parse.User.logOut();
  } else {
    alert('SERVICE CONNECTION ERROR! Please try again later!');
  }
});
```

#### What behavior are you expecting?
main.js is generated properly and uglify processed the main.js file as part of the build.

**Steps to reproduce:**
1. write a customized src/main.prod.ts in es6 syntax 
2. ionic build

**Which @ionic/app-scripts version are you using?**
0.0.36

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.6.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by danbucholtz** [comment] 2016-10-18 02:58
@alamusi,

Can you post your `tsconfig` in here?

Thanks,
Dan

**Comment by alamusi** [comment] 2016-10-18 05:16
@danbucholtz sure thing. see below. should be the same one after RC0 update.

```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "target": "es5"
  },
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```

**Comment by danbucholtz** [comment] 2016-10-18 14:23
@alamusi,

Hmm, that is strange. Can you give us a repo with a recreation of this? We'll look into.

Thanks,
Dan

**Comment by alamusi** [comment] 2016-10-20 00:48
@danbucholtz 

it is indeed strange and happened after RC1 update. my repo is too big. i have to create something smaller. let me see what i can do.

thanks,
alamusi

**Comment by danbucholtz** [comment] 2016-10-20 03:52
@alamusi,

Sounds good. I was almost certain you were going to be using Typescript `2.1` and using a target of `es2015` instead of `es5`. I am a little stumped by this one, so if you can reproduce it, it'd be very helpful.

Thanks,
Dan

**Comment by alamusi** [comment] 2016-10-20 06:48
@danbucholtz

I thought the same and scratched my head on why this happened too.

ionic serve (with transpile) worked as expected and generated everything in es5. while ionic build (with ngc) generated everything else in es5, except the main.prod. that got me suspecting whether this had anything to do with ngc or its config.

thanks
alamusi

**Comment by danbucholtz** [comment] 2016-10-28 06:33
@alamusi,

Any update on this?

Thanks,
Dan

**Comment by alamusi** [comment] 2016-10-28 08:08
@danbucholtz 

my apologies for taking so long. this week has been... chaotic

here is a repo that can reproduce the issue. 
https://github.com/alamusi/issue190

as described above, i modified the main.dev.ts and main.prod.ts with es6 syntax. this is where the file was NOT compiled to es5, when issue the build command (works fine with serve).

of course, i used a setTimeout, which the error appears to be slightly different (same result as issue 206)
```
Alamusis-MacBook-Pro:issue190 alamusi$ ionic build

Running 'build:before' npm script before build

> homes51@ build /Users/alamusi/git/issue190
> ionic-app-scripts build

[00:54:34]  ionic-app-scripts 0.0.36 
[00:54:34]  build prod started ... 
[00:54:34]  clean started ... 
[00:54:34]  clean finished in 6 ms 
[00:54:34]  copy started ... 
[00:54:34]  ngc started ... 
[00:54:34]  copy finished in 100 ms 
[00:54:35]  lint started ... 
[00:54:36]  lint finished in 1.28 s 
[00:54:47]  ngc finished in 12.60 s 
[00:54:47]  bundle started ... 
[00:54:54]  bundle finished in 6.86 s 
[00:54:54]  uglifyjs started ... 
[00:54:54]  sass started ... 
JS_Parse_Error {
  message: 'SyntaxError: Unexpected token: punc ())',
  filename: '/Users/alamusi/git/issue190/www/build/main.js',
  line: 69258,
  col: 12,
  pos: 2644743,
  stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/Users/alamusi/git/issue190/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1545:18)\n    at js_error (eval at <anonymous> (/Users/alamusi/git/issue190/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1553:11)\n    at croak (eval at <anonymous> (/Users/alamusi/git/issue190/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2092:9)\n    at token_error (eval at <anonymous> (/Users/alamusi/git/issue190/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2100:9)\n    at unexpected (eval at <anonymous> (/Users/alamusi/git/issue190/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2106:9)\n    at expr_atom (eval at <anonymous> (/Users/alamusi/git/issue190/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2621:13)\n    at maybe_unary (eval at <anonymous> (/Users/alamusi/git/issue190/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2795:19)\n    at expr_ops (eval at <anonymous> (/Users/alamusi/git/issue190/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2830:24)\n    at maybe_conditional (eval at <anonymous> (/Users/alamusi/git/issue190/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2835:20)\n    at maybe_assign (eval at <anonymous> (/Users/alamusi/git/issue190/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2859:20)\n    at expression (eval at <anonymous> (/Users/alamusi/git/issue190/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2878:20)' }
[00:54:55]  uglifyjs failed: SyntaxError: Unexpected token: punc ()) 
[00:54:55]  ionic-app-script task: "build" 
[00:54:55]  Error: SyntaxError: Unexpected token: punc ()) 

```

**Comment by jgw96** [comment] 2016-10-28 12:45
Hello! I am going to be closing this one as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/239. Thanks!

**Closed by jgw96** 2016-10-28 12:45 UTC
Labels: needs_reply
