### ISSUE TITLE
Feature: cache busting

### ISSUE THREAD

**Issue by Manduro** [driftyco/ionic-app-scripts#249] opened 2016-10-27 09:36 UTC
When using Ionic as a web app, cache busting is essential to make sure your users are always running the latest version.

The best way to do this is by appending a hash to filenames in the build phase. This will make sure that any changed files will be instantly refetched by the browser, but it can safely cache everything that hasn't changed.

The Angular CLI does a great job at this and I would love to see support for this in Ionic. For the JS and CSS files, but also for other assets like images and fonts.

cc @jasekiw who asked questions about this in #201

**Comment by jgw96** [comment] 2016-10-27 16:37
Hello! I have reopened issue #201 as it was a misunderstanding on my part. Sorry about that! I am going to close this one for now as a duplicate of #201 . Thanks!

**Closed by jgw96** 2016-10-27 16:37 UTC
