### ISSUE TITLE
uglifyjs failed: SyntaxError: Unexpected token: name (_View_Item_Host0) 

### ISSUE THREAD

**Issue by NoNameProvided** [driftyco/ionic-app-scripts#237] opened 2016-10-25 14:16 UTC
#### Short description of the problem:

The `ionic-app-script` uglifyjs task is failing all the time after updating to RC.1 when building in production mode for devices.

When I try to build for any device, the build task fails with the following error:

```
[15:25:09]  ionic-app-scripts 0.0.37 
[15:25:09]  build prod started ... 
[15:25:09]  clean started ... 
[15:25:09]  clean finished in 1 ms 
[15:25:09]  copy started ... 
[15:25:09]  ngc started ... 
[15:25:09]  copy finished in 293 ms 
[15:25:09]  lint started ... 
[15:25:12]  lint finished in 3.20 s 
[15:25:43]  ngc finished in 34.72 s 
[15:25:43]  webpack started ... 
[15:25:56]  webpack finished in 12.88 s 
[15:25:56]  uglifyjs started ... 
[15:25:56]  sass started ... 
[15:25:57]  uglifyjs failed: SyntaxError: Unexpected token: name (_View_Item_Host0) 
[15:25:57]  ionic-app-script task: "build" 
[15:25:57]  Error: SyntaxError: Unexpected token: name (_View_Item_Host0) 
```

If I pass the `--dev` flag it works correctly.

On RC.0 (with one of the previous version of `ionic-app-script`) this was working properly. 

#### What behavior are you expecting?

Production build works as well. 

**Steps to reproduce:**
1. Try to make a production build with optimizing
2. See that it fails when try to uglify the source code

```
// not yet
```

**Which @ionic/app-scripts version are you using?** `0.0.37`

**Other information:** 

I would like to get some hint where to look for the generated file to inspect it. I think the one in the `www` folder is from the working debug builds.

**Comment by jgw96** [comment] 2016-10-25 20:04
Hello, thanks for using Ionic! Unfortunately I cannot reproduce this issue. Could you post a repo that I could use to reproduce this issue?

**Comment by jgw96** [comment] 2016-10-28 12:44
Hello, I am going to be closing this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/239. Thanks!

**Closed by jgw96** 2016-10-28 12:44 UTC
Labels: needs_reply
