### ISSUE TITLE
www/index.html is not updated when I change src/index.html

### ISSUE THREAD

**Issue by fpolimen** [driftyco/ionic-app-scripts#208] opened 2016-10-20 19:22 UTC
#### Short description of the problem:
If I modify src/index.html file (for example adding a script) like in the example (http://www.joshmorony.com/ionic-2-how-to-use-google-maps-geolocation-video-tutorial/), and I run "ionic serve" command. The first time it will generate www/index.html file as expected.

When I change again the src/index.html file and I re-run the "ionic serve" command the www/index.html doesn't update to reflect the changes, I have to remove it to let "ionic serve" regenerate.

The other html files under pages directory are correctly regenerated.

#### What behavior are you expecting?

I would expect that the www/ionic.html file is updated and aligned the src/index.html file otherwise the app will not take the new scripts that you will add into index.html

**Steps to reproduce:**
Simplified,

1. Create a new ionic 2 project and execute it: 
ionic start mytest blank --v2
cd mytest
run: ionic serve
stop it (q into the terminal)

it generated a new www/index.html file copying the original src/index.html

2. Modify the original src/index.html and re-execute ionic serve:
I added the line <script src="http://maps.google.com/maps/api/js"></script>
just before <script src="cordova.js"></script>

run ionic serve 
stop it again

3. Verify that the www/index.html has not been updated

www/index.html is not updated with the new line so the behavior of the app will be as the google maps api is not loaded.

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**
in the package.json I see "@ionic/app-scripts@0.0.36"

I am using Ionicframework 2 rc1

My environment is:
{ npm: '3.10.3',
ares: '1.10.1-DEV',
http_parser: '2.7.0',
icu: '57.1',
modules: '48',
node: '6.7.0',
openssl: '1.0.2j',
uv: '1.9.1',
v8: '5.1.281.83',
zlib: '1.2.8' }

OS : macOS Sierra

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by jgw96** [comment] 2016-10-20 19:24
Hello, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/93.

**Closed by jgw96** 2016-10-20 19:24 UTC
