### ISSUE TITLE
Sass build fails if `light` color is not present.

### ISSUE THREAD

**Issue by JustinPierce** [driftyco/ionic-app-scripts#135] opened 2016-10-11 22:44 UTC
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:

The Sass portion of the Ionic 2 RC0 build process will fail with the following message if a color named `light` is not present in the color map in `variables.scss`:

```
[17:39:58]  Sass Error: line: 80, column: 3


  The value `` must be a color.
  If you are setting the value as a map make sure
  both the base and contrast are defined as colors.

  For example:

  $colors: (
    primary:    #327eff,
    secondary:  (base: #32db64, contrast: #000),
  );
[17:39:58]  sass failed:  Sass compile error
Error running ionic app script "build": Error: Sass compile error
```

#### What behavior are you expecting?

As the comment in `variables.scss` claims that the only required color name is `primary`, I would expect compilation to succeed if none of the other color names are defined.

**Steps to reproduce:**
1. Create a new Ionic project (I used `ionic start test --v2`).
2. Remove the `light` color from `variables.scss` at line 29.
3. Attempt to build with `npm run build`.

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**

`ionic-app-scripts 0.0.30`

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by brandyscarney** [comment] 2016-10-11 22:52
Thanks for the issue! This is a duplicate of https://github.com/driftyco/ionic/issues/8266 and it will be fixed in Ionic itself. :)

**Closed by brandyscarney** 2016-10-11 22:52 UTC
