### ISSUE TITLE
typescript compilation  slow in In development in 0.0.36

### ISSUE THREAD

**Issue by 791060555** [driftyco/ionic-app-scripts#210] opened 2016-10-21 01:00 UTC
In development, the development of the compilation of HTML and sass 0.0.36 in soon
But. Ts modified compilation is still very slow, I know the previous gulp up to 3 s

[08:56:15]  watch ready
[08:56:27]  transpile update started ...
[08:56:30]  transpile update finished in 2.43 s
[08:56:30]  bundle update started ...
JS changed:   D:\code\cutePuppyPics\www\build\main.js
[08:56:37]  bundle update finished in 7.09 s
[08:56:37]  watch ready
[08:56:41]  transpile update started ...
[08:56:43]  transpile update finished in 2.46 s
[08:56:43]  bundle update started ...
[08:56:51]  bundle update finished in 7.21 s
[08:56:51]  watch ready
JS changed:   D:\code\cutePuppyPics\www\build\main.js
[08:56:54]  transpile update started ...
[08:56:57]  transpile update finished in 3.20 s
[08:56:57]  bundle update started ...
JS changed:   D:\code\cutePuppyPics\www\build\main.js
[08:57:05]  bundle update finished in 8.12 s
[08:57:05]  watch ready

**Comment by jgw96** [comment] 2016-10-21 12:13
Hello, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/47.

**Closed by jgw96** 2016-10-21 12:13 UTC
